### ISSUE TITLE
下载不来

### ISSUE THREAD

**Issue by xie123** [didi/booster#1]
![image](https://user-images.githubusercontent.com/7463283/56779457-adb9a880-680d-11e9-9e58-75fe1ee13bcc.png)

**Comment by johnsonlee** [comment]
同步到中心仓库还需要一段时间，请耐心等待

**Comment by MichaelJokAr** [comment]
一样的问题

**Comment by minminaya** [comment]
too

**Comment by johnsonlee** [comment]
在 `repositories` 中加上这行试试：

```groovy
maven { url 'https://oss.sonatype.org/content/repositories/public' }
```

**Comment by donglua** [comment]
> 在 `repositories` 中加上这行试试：
> 
> ```groovy
> maven { url 'https://oss.sonatype.org/content/repositories/public' }
> ```

可以了

**Comment by johnsonlee** [comment]
已经同步到 [Maven Central](https://search.maven.org/search?q=com.didiglobal.booster) 了

**Comment by xie123** [comment]
ext.booster_version = '0.1.2-SNAPSHOT'
我的  classpath 'com.android.tools.build:gradle:3.4.0'
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip

![image](https://user-images.githubusercontent.com/7463283/56857616-80eaca00-69a2-11e9-801b-c53b3f25b62c.png)

**Comment by johnsonlee** [comment]
> ext.booster_version = '0.1.2-SNAPSHOT'
> 我的 classpath 'com.android.tools.build:gradle:3.4.0'
> distributionUrl=https://services.gradle.org/distributions/gradle-5.1.1-all.zip
> 
> ![image](https://user-images.githubusercontent.com/7463283/56857616-80eaca00-69a2-11e9-801b-c53b3f25b62c.png)

SNAPSHOT 版本请在 `repositories` 里加上：

```groovy
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
```

**Comment by xie123** [comment]
> > ext.booster_version ='0.1.2-SNAPSHOT' 
> > 我的classpath'com.android.tools.build: gradle:3.4.0'distributionUrl 
> > = [https://services.gradle.org/distributions/gradle-5.1.1-all 。压缩](https://services.gradle.org/distributions/gradle-5.1.1-all.zip)
> > ![图片](https://user-images.githubusercontent.com/7463283/56857616-80eaca00-69a2-11e9-801b-c53b3f25b62c.png)
> 
> SNAPSHOT版本请在`repositories`里加上：
> 
> ```groovy
> maven {url'https ： //oss.sonatype.org/content/repositories/snapshots/ ' }
> ```

加了的 
![image](https://user-images.githubusercontent.com/7463283/56857665-04a4b680-69a3-11e9-945a-b842c705ba26.png)

**Comment by johnsonlee** [comment]
> > > ext.booster_version ='0.1.2-SNAPSHOT'
> > > 我的classpath'com.android.tools.build: gradle:3.4.0'distributionUrl
> > > = [https://services.gradle.org/distributions/gradle-5.1.1-all 。压缩](https://services.gradle.org/distributions/gradle-5.1.1-all.zip)
> > > ![图片](https://user-images.githubusercontent.com/7463283/56857616-80eaca00-69a2-11e9-801b-c53b3f25b62c.png)
> > 
> > 
> > SNAPSHOT版本请在`repositories`里加上：
> > ```groovy
> > maven {url'https ： //oss.sonatype.org/content/repositories/snapshots/ ' }
> > ```
> 
> 加了的
> ![image](https://user-images.githubusercontent.com/7463283/56857665-04a4b680-69a3-11e9-945a-b842c705ba26.png)

`0.1.2-SNAPSHOT` 版本已经上传了：https://oss.sonatype.org/content/repositories/snapshots/com/didiglobal/booster/booster-android-bugfix-toast/

请检查一下网络、配置再重试一下

**Comment by xie123** [comment]
> > > > ext.booster_version ='0.1.2-SNAPSHOT'
> > > > 我的classpath'com.android.tools.build: gradle:3.4.0'distributionUrl
> > > > = [https://services.gradle.org/distributions/gradle-5.1.1-all 。压缩](https://services.gradle.org/distributions/gradle-5.1.1-all.zip)
> > > > ![图片](https://user-images.githubusercontent.com/7463283/56857616-80eaca00-69a2-11e9-801b-c53b3f25b62c.png)
> > > 
> > > 
> > > SNAPSHOT版本请在`repositories`里加上：
> > > ```groovy
> > > maven {url'https ： //oss.sonatype.org/content/repositories/snapshots/ ' }
> > > ```
> > 
> > 
> > 加了的
> > ![image](https://user-images.githubusercontent.com/7463283/56857665-04a4b680-69a3-11e9-945a-b842c705ba26.png)
> 
> `0.1.2-SNAPSHOT` 版本已经上传了：https://oss.sonatype.org/content/repositories/snapshots/com/didiglobal/booster/booster-android-bugfix-toast/
> 
> 请检查一下网络、配置再重试一下

重新弄了下，确实没有下来，gradle的缓存中没有 0.1.2-SNAPSHOT

![image](https://user-images.githubusercontent.com/7463283/56858027-a8439600-69a6-11e9-9655-e958c80cff7a.png)

**Comment by johnsonlee** [comment]
> > > > > ext.booster_version ='0.1.2-SNAPSHOT'
> > > > > 我的classpath'com.android.tools.build: gradle:3.4.0'distributionUrl
> > > > > = [https://services.gradle.org/distributions/gradle-5.1.1-all 。压缩](https://services.gradle.org/distributions/gradle-5.1.1-all.zip)
> > > > > ![图片](https://user-images.githubusercontent.com/7463283/56857616-80eaca00-69a2-11e9-801b-c53b3f25b62c.png)
> > > > 
> > > > 
> > > > SNAPSHOT版本请在`repositories`里加上：
> > > > ```groovy
> > > > maven {url'https ： //oss.sonatype.org/content/repositories/snapshots/ ' }
> > > > ```
> > > 
> > > 
> > > 加了的
> > > ![image](https://user-images.githubusercontent.com/7463283/56857665-04a4b680-69a3-11e9-945a-b842c705ba26.png)
> > 
> > 
> > `0.1.2-SNAPSHOT` 版本已经上传了：https://oss.sonatype.org/content/repositories/snapshots/com/didiglobal/booster/booster-android-bugfix-toast/
> > 请检查一下网络、配置再重试一下
> 
> 重新弄了下，确实没有下来，gradle的缓存中没有 0.1.2-SNAPSHOT
> 
> ![image](https://user-images.githubusercontent.com/7463283/56858027-a8439600-69a6-11e9-9655-e958c80cff7a.png)

强制刷新试试：在命令行加上 `--refresh-dependencies`

**Comment by xie123** [comment]
绝缘了哦，还是一样的。

**Comment by johnsonlee** [comment]
试试把 `snapshot repo` 移到 `repositories` 的最前面：

```groovy
repositories {
    maven {url'https ： //oss.sonatype.org/content/repositories/snapshots/ ' }
    google()
    mavenCentral()
    jcenter()
}
```

**Comment by xie123** [comment]
![image](https://user-images.githubusercontent.com/7463283/56858226-74b63b00-69a9-11e9-9705-0df761cce81b.png)
两边都要加 才能行，-.- !

**Comment by johnsonlee** [comment]
> ![image](https://user-images.githubusercontent.com/7463283/56858226-74b63b00-69a9-11e9-9705-0df761cce81b.png)
> 两边都要加 才能行，-.- !

对的，`booster-android-bugfix-toast` 是 Android project 依赖的项（在 transform  时被 Booster 注入的）
