### ISSUE TITLE
booster-task-compression remove resources randomly

### ISSUE THREAD

**Issue by zjn0505** [didi/booster#103]
- System version
macOS 10.15
- Java version
1.8
- Gradle version
5.4.1
- Android Gradle plugin version
3.5.1
- Booster version
0.25.0
- Stack traces
[report.txt](https://github.com/didi/booster/files/3718282/report.txt)

I found that booster is removing AppCompat resources randomly.

`abc_ic_menu_cut_mtrl_alpha.png` and `abc_ic_menu_copy_mtrl_am_alpha.png` are introduced by 
 Androidx AppCompat 1.1.0 under `drawable-mdpi-v4`, `drawable-hdpi-v4`, `drawable-ldrtl-mdpi-v17`... These pngs are different in size across these folders, and in `ldrtl` folders, they are mirrored.

When `booster-task-compress` is enabled, these two files may get randomly removed from some of these places and caused irreproducible builds.

This issue can be reproduced in an empty hello world project from Android Studio with Booster enabled.

I think it could be better if we can have `ldrtl` resource folders from AppCompat removed when `supportsRtl=false`, also I don't know what is the purpose to have resources like `layout-watch-v20` and `drawable-watch-v20` in the artifact apk when it is a mobile only application. If they are useless for real, it would be nice if we can have them removed with booster task.

**Comment by zjn0505** [comment]
I see in the code the resources are sorted by screen density, maybe this is the reason. Drawables under `ldrtl` are categorized as same density to their counterparts. So one of them will be picked and removed.

https://github.com/didi/booster/blob/6d19c786de8b2a82af7e621ee0dc447ffcdc94b0/booster-task-compression/src/main/kotlin/com/didiglobal/booster/task/compression/RemoveRedundantFlatImages.kt#L33

**Comment by johnsonlee** [comment]
> I don't know what is the purpose to have resources like layout-watch-v20 and drawable-watch-v20 in the artifact apk when it is a mobile only application. If they are useless for real, it would be nice if we can have them removed with booster task.

Good idea! We are going to add it to features roadmap

**Comment by johnsonlee** [comment]
Please try the latest snapshot version `0.26.0-SNAPSHOT`

**Comment by zjn0505** [comment]
> Please try the latest snapshot version `0.26.0-SNAPSHOT`

Verified with `0.26.0-SNAPSHOT`, checked resources removal on `supportsRtl=true` and `false`.

Since `.9.png` files are ignored, they are neither processed for png compression, nor in the step of redundancy removal. Therefore, there are still `ldrtl` folders containing `abc_spinner_mtrl_am_alpha.9.png` when `supportsRtl=false`
