### ISSUE TITLE
项目编译失败

### ISSUE THREAD

**Issue by Fredlxy** [didi/booster#106]
ERROR: Could not get unknown property 'OSSRH_USERNAME' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer. Open File

**Comment by johnsonlee** [comment]
Those properties starts with `OSSRH_` are only used for publishing, if you just want to build this project, try to config `OSSRH_USERNAME` and `OSSRH_PASSWORD` in your local properties or global gradle properties file `~/.gradle/gradle.properties`
