### ISSUE TITLE
编译失败、打包失败

### ISSUE THREAD

**Issue by snpmyn** [didi/booster#108]
Please provide the following informations.

- System version
29
- Java version
1.8
- Gradle version
5.4.1
- Android Gradle plugin version
3.5.1
- Booster version
0.26.0
- Stack traces
打包productRelease（构建变体为product，构建类型为release）成功。除此之外，其它的都打包失败。

**Comment by johnsonlee** [comment]
具体的失败原因有吗？试试最新的版本 `0.26.1`

**Comment by snpmyn** [comment]
> 具体的失败原因有吗？试试最新的版本 `0.26.1`

是因为没有开启混淆的原因吗？我开启混淆后，打包就正常了。体积从13.6M降到了5.8M，很可观。

顺带问一下，项目中使用到了JitPack，但是使用的是SNAPT临时版本，这个如果在正式版使用，不会和Booster冲突吧？

**Comment by neighbWang** [comment]
和混淆没关系。您能使用 `./gradlew  xxx --stacktrace` 命令来提供下相应错误信息么？或者提供一个sample工程给我。

**Comment by snpmyn** [comment]
> 和混淆没关系。您能使用 `./gradlew xxx --stacktrace` 命令来提供下相应错误信息么？或者提供一个sample工程给我。

现在正常了，不报错了。期望接下一路正常~~~
