### ISSUE TITLE
build.gradle根据文档修改后，出现报错

### ISSUE THREAD

**Issue by ShPG** [didi/booster#11]
报错信息：
Gradle 'XXX' project refresh failed
Error:Cause: compileSdkVersion is not specified.

但是我的compileSdkVersion已经写过了。

**Comment by johnsonlee** [comment]
请提供 `build.gradle` 的内容

**Comment by ShPG** [comment]
java 1.8.0_162
gradle 4.5
gradle plugin 3.1.4

**Comment by johnsonlee** [comment]
> java 1.8.0_162
> gradle 4.5
> gradle plugin 3.1.4

麻烦粘一下 `build.grald` 里的配置

**Comment by johnsonlee** [comment]
请参考以下配置：

```
.
├── app
│   ├── app.iml
│   ├── build
│   ├── build.gradle
│   ├── libs
│   ├── proguard-rules.pro
│   └── src
├── build.gradle
├── demo.iml
├── gradle
│   └── wrapper
├── gradle.properties
├── gradlew
├── gradlew.bat
├── local.properties
└── settings.gradle
```

## `${projectDir}/build.gradle`

```groovy
buildscript {
    ext.kotlin_version = '1.3.11'
    ext.booster_version = '0.1.4'
    repositories {
        mavenLocal()
        maven {
            url 'http://artifactory.intra.xiaojukeji.com/artifactory/public/'
        }
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
        classpath "com.didiglobal.booster:booster-task-all:$booster_version"
        classpath "com.didiglobal.booster:booster-transform-all:$booster_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}
```

##  `${projectDir}/app/build.gradle`

```groovy
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.didiglobal.booster'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.didiglobal.booster.demo"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
}
```

**Comment by ShPG** [comment]
我没有导kotlin，难道必须导入？
或者不支持ext这种写法？

### ${projectDir}/build.gradle
buildscript {
    ext.booster_version = '0.1.4'
    repositories {
        jcenter()
        google()
        mavenCentral()
        maven {
            url "https://jitpack.io"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
        classpath "com.didiglobal.booster:booster-task-all:$booster_version"
        classpath "com.didiglobal.booster:booster-transform-all:$booster_version"
    }

}

apply plugin: 'com.android.application'
apply plugin: 'com.didiglobal.booster'

allprojects {

    repositories {
        jcenter()
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://dl.bintray.com/thelasterstar/maven/" }
        flatDir {
            dirs '../fundbase/libs'
      }
   }

ext{
        androidCompileSdkVersion = 28
        androidBuildToolsVersion = '28.0.0'
        androidApplicationId = 'com.xxx'
        androidMinSdkVersion = 14
        androidTargetSdkVersion = 28
}


### ${projectDir}/app/build.gradle

apply plugin: 'com.android.application'
apply plugin: 'com.didiglobal.booster'

android {
   compileSdkVersion parent.ext.androidCompileSdkVersion
    buildToolsVersion parent.ext.androidBuildToolsVersion

  defaultConfig {
        minSdkVersion parent.ext.androidMinSdkVersion
        targetSdkVersion parent.ext.androidTargetSdkVersion
        versionCode parent.ext.androidVersionCode
        versionName parent.ext.androidVersionName
        applicationId parent.ext.androidApplicationId
        manifestPlaceholders = [CHANNEL_NAME: "Unspecified"]
        ndk {
            abiFilters "armeabi"
        }
        multiDexEnabled true
    }


       buildTypes {

        release {
            aaptOptions.cruncherEnabled = false
            aaptOptions.useNewCruncher = false
            shrinkResources true
            zipAlignEnabled true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            signingConfig signingConfigs.release
            buildConfigField("Boolean","Environment","true")

            applicationVariants.all { variant ->
                variant.outputs.all{
                    outputFileName = "${variant.name}-${variant.versionName}.apk"
                }
            }
        }
        debug{
            signingConfig signingConfigs.release
            buildConfigField("Boolean","Environment","false")
        }

    }

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
}

}

**Comment by johnsonlee** [comment]
把 `ext` 放到 `buildscript` 里：

```groovy
ext{
    androidCompileSdkVersion = 28
    androidBuildToolsVersion = '28.0.0'
    androidApplicationId = 'com.xxx'
    androidMinSdkVersion = 14
    androidTargetSdkVersion = 28
}
```

**Comment by johnsonlee** [comment]
`Booster v0.2.0` is available

**Comment by lishuliang28** [comment]
出现类似问题。

buildscript {
    ext.booster_version = '0.22.0'
    repositories {
        jcenter()
        google()
        maven { url 'https://oss.sonatype.org/content/repositories/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'


        classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
        classpath "com.didiglobal.booster:booster-task-all:$booster_version"
        classpath "com.didiglobal.booster:booster-transform-all:$booster_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        google()
        maven {
            url "http://mvn.gt.igexin.com/nexus/content/repositories/releases/"
        }
        maven{
            url 'https://oss.sonatype.org/content/repositories/public'
        }
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.didiglobal.booster'
