### ISSUE TITLE
IllegalAccessError

### ISSUE THREAD

**Issue by heheheheheheheheh** [didi/booster#118]
和阿里的sophix有诸多冲突,
booster-transform-shared-preferences在sophix打补丁应用后出现空指针异常:context为空.
booster-transform-finalizer-watchdog-daemon在打补丁应用后在华为BAH2-W09机型上出现:
java.lang.IllegalAccessError: Illegal class access: 'com.didiglobal.booster.instrument.FinalizerWatchdogDaemonKiller' attempting to access 'com.didiglobal.booster.instrument.FinalizerWatchdogDaemonKiller$1'

**Comment by neighbWang** [comment]
这个和Sp的Context的初始化时机有关系。sophix是在onCreate方法初始化，booster-transform-shared-preferences的逻辑在attachBaseContext()方法初始化，稍后我们修复下。

**Comment by neighbWang** [comment]
试试 booster-android-instrument-shared-preferences:1.5.0-SNAPSHOT和booster-transform-finalizer-watchdog-daemon:1.5.0-SNAPSHOT版本？

**Comment by zhaodexi** [comment]
使用1.5.1版本booster-transform-finalizer-watchdog-daemon，依然出现java.lang.IllegalAccessError: Illegal class access: 'com.didiglobal.booster.instrument.FinalizerWatchdogDaemonKiller' attempting to access 'com.didiglobal.booster.instrument.FinalizerWatchdogDaemonKiller$1'问题
