### ISSUE TITLE
怎么监控三方使用的线程

### ISSUE THREAD

**Issue by xiaowj** [didi/booster#12]
并没有在项目中找到相关监控线程的代码

**Comment by johnsonlee** [comment]
在 Booster `v1.0` 中实现，敬请关注 Booster 的动态

**Comment by xiaowj** [comment]
这就尴尬了。。

**Comment by johnsonlee** [comment]
> 这就尴尬了。。

很快的

**Comment by xiaowj** [comment]
> > 这就尴尬了。。
> 
> 很快的

赞，已经看到commit了

**Comment by johnsonlee** [comment]
`Booster v0.2.0` is available
