### ISSUE TITLE
supported "booster.task.compression.pngquant.bin" 

### ISSUE THREAD

**Issue by LinXiaoTao** [didi/booster#137]
- Booster version
  1.30.0

Why is the `booster.task.compression.pngquant.bin` property not supported?
[This commit](https://github.com/didi/booster/commit/5f0087ddf9ef83f5f7ca6487e2da0e983c46ec8e#diff-ecd3ed5ca1dd7e5e34476a0a83c47bbf)

<img width="1254" alt="QQ20200203-111539@2x" src="https://user-images.githubusercontent.com/19836925/73623351-9dc1d580-4677-11ea-8b3e-f961ad00369e.png">

**Comment by johnsonlee** [comment]
To improve the user experience, [booster-pngquant-provider](https://github.com/johnsonlee/booster-pngquant-provider) has been created to compress images by pngquant without installation

**Comment by LinXiaoTao** [comment]
@johnsonlee 谢谢回复，希望及时更新下文档哈。
