### ISSUE TITLE
构建完成后，没有生成build/reports目录

### ISSUE THREAD

**Issue by FredLiu111** [didi/booster#14]
目前构建完成release包后，没有找到 build/reports/ 目录, 现版本有这项功能吗？
Booster  v 0.1.5
Gradle  v 4.4
com.android.tools.build:gradle:3.1.2'

**Comment by johnsonlee** [comment]
`Booster v0.1.6` 还未release，可以试试 `0.1.6-SNAPSHOT`

**Comment by johnsonlee** [comment]
`Booster v0.1.6` is available
