### ISSUE TITLE
booster不兼容Android Gradle plugin 3.6.0以上，安装失败 INSTALL_FAILED_INVALID_APK

### ISSUE THREAD

**Issue by MankinChung** [didi/booster#145]
Please provide the following informations.

- System version 
9.0
- Java version
1.8
- Gradle version 
5.6.4-6.2.1
- Android Gradle plugin version
3.6.0-3.6.1
- Booster version
1.2.0-1.4.0
- Stack traces

Failed to commit install session 1039818027 with command cmd package install-commit 1039818027. Error: INSTALL_FAILED_INVALID_APK: Package couldn't be installed in /data/app/xxxxxx: Package /data/app/xxxxxx/base.apk code is missing

**Comment by johnsonlee** [comment]
AGP 3.6.0  变化比较大，等官方正式发布后再做适配
