### ISSUE TITLE
webview冷启动不兼容android Q

### ISSUE THREAD

**Issue by duan101101** [didi/booster#153]
Please provide the following informations.
通过那个反射拿不到目标方法了

- System version
Q
- Java version

- Gradle version

- Android Gradle plugin version

- Booster version

- Stack traces

**Comment by johnsonlee** [comment]
已知问题

**Comment by johnsonlee** [comment]
亲测 *HUAWEI P30 Android 10* 没问题，麻烦提供一下机型信息

**Comment by duan101101** [comment]
> 亲测 _HUAWEI P30 Android 10_ 没问题，麻烦提供一下机型信息

pixel 2

**Comment by johnsonlee** [comment]
> > 亲测 _HUAWEI P30 Android 10_ 没问题，麻烦提供一下机型信息
> 
> pixel 2

别的机型试过吗？

**Comment by duan101101** [comment]
> > > 亲测 _HUAWEI P30 Android 10_ 没问题，麻烦提供一下机型信息
> > 
> > 
> > pixel 2
> 
> 别的机型试过吗？

老的系统没问题，手上没有别的10的设备了
