### ISSUE TITLE
编译完成没有生成 html

### ISSUE THREAD

**Issue by Modificator** [didi/booster#16]
AGP version：3.3.2
Gradle version：4.10.1/5.1.1
booster version：0.1.5/0.1.6/0.2.0
试过  app:assembleNormalRelease, assembleNormalRelease, assembleRelease
删掉 productFlavors，app:assembleRelease, assembleRelease
都不行，都没有生成 html 
![image](https://user-images.githubusercontent.com/3425930/57204739-34c80700-6fec-11e9-8f1a-039143c536ac.png)

**Comment by johnsonlee** [comment]
reports 目录下以各个模块命名的目录里就有对应的报告，`booster-transform-lint` 模块输出的报告是 `*.dot` 格式，需要自己转成图片或者 PDF 格式

**Comment by Modificator** [comment]
哦哦，html 是 lint 输出的，新建的项目里没关掉 lint 才会有的
