### ISSUE TITLE
将booster-gradle-plugin改成buildSrc

### ISSUE THREAD

**Issue by zhairui** [didi/booster#163]
大佬好，请教下，我想将booster-gradle-plugin改成buildSrc方便我调试，但是在依赖其它module时，报错了
Project with path ':booster-transform-util' could not be found in project ':buildSrc'.

想问下，怎么解决这个问题哈。谢谢

**Comment by johnsonlee** [comment]
需要在工程的 `settings.gradle` 中把 Booster 的模块 `include` 进去，例如：

```gradle
include ':booster-transform-util'
project(':booster.transform.util').projectDir = '......'
```

**Comment by zhairui** [comment]
settings.gradle
`project(':booster-transform-util').projectDir = "$rootDir/booster-transform-util" as File`

buildSrc/build.gradle
`implementation project(':booster-transform-util')`

大佬，我这样写有啥子问题嘛，还是会报错。

感谢！

**Comment by johnsonlee** [comment]
> settings.gradle
> `project(':booster-transform-util').projectDir = "$rootDir/booster-transform-util" as File`
> 
> buildSrc/build.gradle
> `implementation project(':booster-transform-util')`
> 
> 大佬，我这样写有啥子问题嘛，还是会报错。
> 
> 感谢！

```gradle
project(':booster-transform-util').projectDir = File("$rootDir/booster-transform-util")
```
