### ISSUE TITLE
com.google.common.io.Files.fileTreeTraverser()Lcom/google/common/collect/TreeTraverser; from class com.android.utils.FileUtils

### ISSUE THREAD

**Issue by lijingxin888** [didi/booster#171]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'.
> tried to access method com.google.common.io.Files.fileTreeTraverser()Lcom/google/common/collect/TreeTraverser; from class com.android.utils.FileUtils

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 33s
80 actionable tasks: 8 executed, 72 up-to-date

报错了，studio 版本是 3.5.1，gradle 版本是5.6.2

**Comment by lijingxin888** [comment]
Booster 版本 1.7.2，
buildscript {
    ext {
        kotlin_version = '1.3.61'
        booster_version = '1.7.2'
    }

    repositories {
        maven {
            url 'https://dl.bintray.com/zouyuhan/maven'
        }
        maven {
            url 'https://maven.aliyun.com/repository/public'
        }
        maven {
            url 'https://maven.aliyun.com/repository/jcenter'
        }
        maven {
            url 'https://maven.aliyun.com/repository/google'
        }
        maven {
            url 'http://mvn.mob.com/android'
        }
        maven { url 'https://jitpack.io' }
        google()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.meituan.android.walle:plugin:1.1.6'
        classpath 'com.mob.sdk:MobSDK-Impl:2019.0812.1014'

        classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
        classpath "com.didiglobal.booster:booster-task-compression-cwebp:$booster_version"
    }
}

**Comment by johnsonlee** [comment]
用上面的版本无法复现，是否还有其它的插件？

**Comment by neighbWang** [comment]
建议使用 `./graldew buildEnv`  查看下 `guava` 依赖的版本号，是否和官方gradle 自身的依赖版本一致。

**Comment by lijingxin888** [comment]
Could not find booster-task-compression-cwebp-2.1.0.jar (com.didiglobal.booster:booster-task-compression-cwebp:2.1.0).
Searched in the following locations:
    https://maven.aliyun.com/repository/public/com/didiglobal/booster/booster-task-compression-cwebp/2.1.0/booster-task-compression-cwebp-2.1.0.jar

**Comment by lijingxin888** [comment]
booster 版本升级到2.1.0，这是咋回事

**Comment by lijingxin888** [comment]
> 建议使用 `./graldew buildEnv` 查看下 `guava` 依赖的版本号，是否和官方gradle 自身的依赖版本一致。

EDZdeMacBook-Pro-6:android_phone xinxin$ ./graldew buildEnv
bash: ./graldew: No such file or directory
 看不了

现在gradle-plugin：4.0.0

**Comment by lijingxin888** [comment]
> > 建议使用 `./graldew buildEnv` 查看下 `guava` 依赖的版本号，是否和官方gradle 自身的依赖版本一致。
> 
> EDZdeMacBook-Pro-6:android_phone xinxin$ ./graldew buildEnv
> bash: ./graldew: No such file or directory
> 看不了
> 
> 现在gradle-plugin：4.0.0，grdle：6.2-bin

**Comment by johnsonlee** [comment]
> booster 版本升级到2.1.0，这是咋回事

去掉 aliyun 镜像试试，可能 aliyun 镜像同步不及时

**Comment by neighbWang** [comment]
现在最新版本还有问题么？

**Comment by JayRichrd** [comment]
> 现在最新版本还有问题么？

还是存在这个问题，下面是我的工程根目录的build.gradle配置
buildscript {
    ext.kotlin_version = '1.3.72'
    ext.booster_version = '2.2.0'
    repositories {
        google()
        jcenter()
        maven { url "https://oss.sonatype.org/content/repositories/public" }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.didiglobal.booster:booster-gradle-plugin:${booster_version}"
    }
}

仅仅加了一个路径，还没有在app/build.gradle中apply插件，编译的时候就会报告如下错误：
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'.
> tried to access method com.google.common.io.Files.fileTreeTraverser()Lcom/google/common/collect/TreeTraverser; from class com.android.utils.FileUtils

**Comment by johnsonlee** [comment]
这个问题的原因是：

`com.google.auto.service:auto-service:1.0-rc6` 依赖的 `com.google.guava:guava:27.0.1-jre` 版本与`com.android.tools.build:gradle:3.2.1` 依赖的 `com.google.guava:guava:23.0` 版本不兼容导致

解决办法：

1. 升级 Android Gradle Plugin 到 `3.4+`
2. 或者强制指定 `guava` 版本为 `com.google.guava:guava:23.0`（不确定有没有其它问题）
3. 或者使用 Booster  `1.3.1` 及以下版本

**Comment by johnsonlee** [comment]
强制指定 `guava` 版本：

```gradle
buildscript {
    ext {
        kotlin_version = 'xxx'
        booster_version = '2.2.0'
    }

    repositories {
        mavenLocal()
        mavenCentral()
        google()
        jcenter()
        maven { url 'https://oss.sonatype.org/content/repositories/public/' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
        // ......
    }

    configurations.all {
        resolutionStrategy.dependencySubstitution {
            substitute(module("com.google.guava:guava"))
                    .with(module("com.google.guava:guava:23.0"))
        }
    }
}
```

**Comment by lijingxin888** [comment]
Cause: connect timed out

**Comment by lijingxin888** [comment]
按照你上面的方法，又出现这个问题

**Comment by johnsonlee** [comment]
> Cause: connect timed out

Maven Central 的问题？下载的是哪个版本？试试优先从 `jcenter()` 下载

**Comment by ouyangpeng** [comment]
> 建议使用 `./graldew buildEnv` 查看下 `guava` 依赖的版本号，是否和官方gradle 自身的依赖版本一致。

写错了，应该是    gradlew buildEnvv

**Comment by johnsonlee** [comment]
> > 建议使用 `./graldew buildEnv` 查看下 `guava` 依赖的版本号，是否和官方gradle 自身的依赖版本一致。
> 
> 写错了，应该是 gradlew buildEnvv

嗯嗯，手误
