### ISSUE TITLE
加入 bootser 以后，android studio 直接调试真实设备，无法安装包的问题，Cause: lateinit property logger has not been initialized

### ISSUE THREAD

**Issue by fuyoushuo-android** [didi/booster#18]
使用 Bootser 以后，可以直接 assemble 命令直接打包，但是 使用android studio pm install 安装包的时候，Cause: lateinit property logger has not been initialized 会出现这个问题，gradle plugin 3.1.1  gradle version 4.6.0
![image](https://user-images.githubusercontent.com/33893836/57501121-d6b36080-7318-11e9-984a-4b7381a92112.png)
![Uploading image.png…]()
请帮忙分析一下

**Comment by johnsonlee** [comment]
试试将 Android Studio *Instant Run* 选项关闭

**Comment by fuyoushuo-android** [comment]
> 试试将 Android Studio _Instant Run_ 选项关闭
和 instant run 没有关系，我已经是关闭状态了
我这个是 assembleRelease 成功，assembleDebug 会失败，那个 compress task 里面那个 Log 没有初始化

**Comment by fuyoushuo-android** [comment]
详细日志如下
![image](https://user-images.githubusercontent.com/33893836/57512925-9a472b00-733f-11e9-8f31-a6780346d333.png)

**Comment by fuyoushuo-android** [comment]
这个问题 0.3.2 已经可以解决了吗

**Comment by johnsonlee** [comment]
`Booster v0.3.1` 就已经修复了

**Comment by fuyoushuo-android** [comment]
> `Booster v0.3.1` 就已经修复了

thanks

**Comment by johnsonlee** [comment]
`booster-task-compression` 增加了对  `pngquant` 的支持（需要本地安装 pngquant），详见：[README](https://github.com/didi/booster/tree/master/booster-task-compression)，
