### ISSUE TITLE
png压缩出错

### ISSUE THREAD

**Issue by Caij** [didi/booster#183]
2.3.1 在不使用booster-pngquant-provider 的情况下  走aapt2压缩
出现错误 error: file not found

**Comment by johnsonlee** [comment]
png压缩需要用到 booster-pngquant-provider

**Comment by johnsonlee** [comment]
除非你本地有安装 pngquant

**Comment by Caij** [comment]
我看到里面有aapt的逻辑以为可以不用  感谢
