### ISSUE TITLE
variant和transform 搞的太好了，妙啊

### ISSUE THREAD

**Issue by JuneLeo** [didi/booster#185]
ClassTransformer和VariantProcessor 的处理很好，妙啊

**Comment by johnsonlee** [comment]
`VariantProcessor` 注入外部库更妙

**Comment by JuneLeo** [comment]
> `VariantProcessor` 注入外部库更妙

大佬，我看了你是通过SPI的方式来处理的，我的理解VariantProcessor 是想通过variant来构建task，VariantProcessor注入外部库是什么意思呢？

**Comment by johnsonlee** [comment]
参考：https://github.com/didi/booster/blob/master/booster-transform-activity-thread/src/main/kotlin/com/didiglobal/booster/transform/activitythread/ActivityThreadVarinatProcessor.kt

**Comment by JuneLeo** [comment]
> 参考：https://github.com/didi/booster/blob/master/booster-transform-activity-thread/src/main/kotlin/com/didiglobal/booster/transform/activitythread/ActivityThreadVarinatProcessor.kt

大佬，在插件中动态引入依赖库的方式有用过的；不过大佬的很多写法，我比较喜欢！

**Comment by JuneLeo** [comment]
> 参考：https://github.com/didi/booster/blob/master/booster-transform-activity-thread/src/main/kotlin/com/didiglobal/booster/transform/activitythread/ActivityThreadVarinatProcessor.kt

大佬的思路清晰，代码层次分明
