### ISSUE TITLE
no need adding sonatype repository?

### ISSUE THREAD

**Issue by yueban** [didi/booster#189]
- Booster version
2.3.1

booster library has already been published to mavenCentral as the image show below. Do we still need to add sonatype repository?

![image](https://user-images.githubusercontent.com/5647837/89984442-f9ff5500-dcab-11ea-8f93-7c34e96ece2b.png)

**Comment by johnsonlee** [comment]
If anyone want to use `SNAPSHOT` version, `sonatype` repository is required.

**Comment by yueban** [comment]
It could be better to add this info in README.

**Comment by johnsonlee** [comment]
> It could be better to add this info in README.

DONE
