### ISSUE TITLE
集成以后，App启动奔溃

### ISSUE THREAD

**Issue by dingbuoyi** [didi/booster#19]
崩溃信息：
 java.lang.RuntimeException: Unable to create application com.xx.xx.MyApplication: org.greenrobot.greendao.DaoException: Could not init DAOConfig

**Comment by johnsonlee** [comment]
在 classpath 中去掉 `booster-transform-shrink`  或者手动加上 ignores 规则，见 ：https://github.com/didi/booster/tree/master/booster-transform-shrink

**Comment by dingbuoyi** [comment]
@johnsonlee 哇塞，回复的那么快，谢谢

**Comment by johnsonlee** [comment]
下个版本考虑把 `constants shrinking` 去掉

**Comment by johnsonlee** [comment]
`Booster v0.3.2` is available

**Comment by duanxifeng** [comment]
请问忽略assets，drawable等资源路径应该怎么配置

**Comment by johnsonlee** [comment]
> 请问忽略assets，drawable等资源路径应该怎么配置

暂时还不支持配置，是有什么特定的需求吗？

**Comment by duanxifeng** [comment]
> > 请问忽略assets，drawable等资源路径应该怎么配置
> 
> 暂时还不支持配置，是有什么特定的需求吗？

集成shrink后发现打包后把一些assets，drawable下资源删了

**Comment by johnsonlee** [comment]
`booster-transform-shrink` 不会删资源文件，只会删除 `R` 文件，如果不想用 `booster-transform-shrink`，可以单独引入其它各个模块：

```
dependencies {
    classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
    classpath "com.didiglobal.booster:booster-task-all:$booster_version"
//    classpath "com.didiglobal.booster:booster-transform-all:$booster_version"
    classpath "com.didiglobal.booster:booster-transform-lint:$booster_version"
    classpath "com.didiglobal.booster:booster-transform-shared-preferences:$booster_version"
    classpath "com.didiglobal.booster:booster-transform-thread:$booster_version"
    classpath "com.didiglobal.booster:booster-transform-toast:$booster_version"
}
```

**Comment by duanxifeng** [comment]
> `booster-transform-shrink` 不会删资源文件，只会删除 `R` 文件，如果不想用 `booster-transform-shrink`，可以单独引入其它各个模块：
> 
> ```
> dependencies {
>     classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
>     classpath "com.didiglobal.booster:booster-task-all:$booster_version"
> //    classpath "com.didiglobal.booster:booster-transform-all:$booster_version"
>     classpath "com.didiglobal.booster:booster-transform-lint:$booster_version"
>     classpath "com.didiglobal.booster:booster-transform-shared-preferences:$booster_version"
>     classpath "com.didiglobal.booster:booster-transform-thread:$booster_version"
>     classpath "com.didiglobal.booster:booster-transform-toast:$booster_version"
> }
> ```

  那是在哪个模块删的呢

**Comment by johnsonlee** [comment]
> > `booster-transform-shrink` 不会删资源文件，只会删除 `R` 文件，如果不想用 `booster-transform-shrink`，可以单独引入其它各个模块：
> > ```
> > dependencies {
> >     classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
> >     classpath "com.didiglobal.booster:booster-task-all:$booster_version"
> > //    classpath "com.didiglobal.booster:booster-transform-all:$booster_version"
> >     classpath "com.didiglobal.booster:booster-transform-lint:$booster_version"
> >     classpath "com.didiglobal.booster:booster-transform-shared-preferences:$booster_version"
> >     classpath "com.didiglobal.booster:booster-transform-thread:$booster_version"
> >     classpath "com.didiglobal.booster:booster-transform-toast:$booster_version"
> > }
> > ```
> 
>   那是在哪个模块删的呢， 单独引入transform确实还是被删了

麻烦粘一下 `booster-transform-shrink` 生成的  *report.txt* 文件，在 *build/reports* 目录下

**Comment by duanxifeng** [comment]
> > > `booster-transform-shrink` 不会删资源文件，只会删除 `R` 文件，如果不想用 `booster-transform-shrink`，可以单独引入其它各个模块：
> > > ```
> > > dependencies {
> > >     classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
> > >     classpath "com.didiglobal.booster:booster-task-all:$booster_version"
> > > //    classpath "com.didiglobal.booster:booster-transform-all:$booster_version"
> > >     classpath "com.didiglobal.booster:booster-transform-lint:$booster_version"
> > >     classpath "com.didiglobal.booster:booster-transform-shared-preferences:$booster_version"
> > >     classpath "com.didiglobal.booster:booster-transform-thread:$booster_version"
> > >     classpath "com.didiglobal.booster:booster-transform-toast:$booster_version"
> > > }
> > > ```
> > 
> > 
> >   那是在哪个模块删的呢， 单独引入transform确实还是被删了
> 
> 麻烦粘一下 `booster-transform-shrink` 生成的 _report.txt_ 文件，在 _build/reports_ 目录下

抱歉，不方便

**Comment by JianGsHanz** [comment]
> 在 classpath 中去掉 `booster-transform-shrink` 或者手动加上 ignores 规则，见 ：https://github.com/didi/booster/tree/master/booster-transform-shrink

请问如果我想ignores一个类，手动添加ignores应该怎么写？是什么样的格式呢？

**Comment by johnsonlee** [comment]
please try the latest version `0.23.0-SNAPSHOT` or `0.23.0`
