### ISSUE TITLE
Analyzer模块静态分析接口方法和抽象方法的支持

### ISSUE THREAD

**Issue by Kyson** [didi/booster#193]
![image](https://user-images.githubusercontent.com/3901140/91942244-3105db00-ed2d-11ea-8ae3-983e6fdfbcf8.png)

模块Analyzer中会构建方法调用图，但是如上图的情况，字段声明为接口或者抽象类，实际字段类型为他们的实现类

这时候调用接口方法或者抽象方法的时候，`methodInsnNode.owner` 拿到的是接口或抽象类，这样的问题就是真正调用的方法的指令没办法继续往下分析了（因为接口owner的方法实际上实现方法为空）

我看booster似乎没有处理这种情况？

**Comment by Kyson** [comment]
补充个想法，事实上这种情况这个字段具体的类型只有运行时才能知道，所以想知道有没有其他什么角度可以解决

**Comment by johnsonlee** [comment]
主要是考虑到分析的性能问题，其实也可以通过 `Thread Annotations` 来辅助 `Analyser`

**Comment by Kyson** [comment]
@johnsonlee 理论上无法做到invoke virtual和invoke interface在编译阶段判定具体的方法位置的话，能否提供一种模式是把疑似可能调用的方法（也就是这个方法所在类的父类和子类中的override方法）全部列出来。。。

**Comment by johnsonlee** [comment]
为 virtual 方法和 override 方法建立一个 edge(virtual, override) 就可以实现了

**Comment by Kyson** [comment]
了解，多谢
