### ISSUE TITLE
Sp方案在4.4手机上Debug直接运行时crash（是在开启instantrun的情况下, 第二次run时会crash, 第一次全新安装时不会）

### ISSUE THREAD

**Issue by HolenZhou** [didi/booster#196]
Please provide the following informations.

- System version 4.4.3

- Java version  8

- Gradle version 5.1.1

- Android Gradle plugin version 3.4.2

- Booster version 2.3.1

- Stack traces

![image](https://user-images.githubusercontent.com/11223102/92456447-83e00680-f1f5-11ea-8db8-ed5edf73da2c.png)

**Comment by neighbWang** [comment]
关闭instant run试试。

**Comment by HolenZhou** [comment]
关掉可以

**Comment by neighbWang** [comment]
instant-run 和很多字节码插件的兼容性不是很好。
