### ISSUE TITLE
Could not initialize class com.didiglobal.booster.gradle.TransformManagerKt

### ISSUE THREAD

**Issue by svenjung** [didi/booster#201]
自定义插件失败
完全照搬的文档里面buildSrc写法，version 为2.4.0

**Comment by johnsonlee** [comment]
详细的堆栈？

**Comment by ChinaZeng** [comment]
我也遇到了这个问题，测试项目源码 地址：https://github.com/ChinaZeng/CTest

**Comment by johnsonlee** [comment]
> 我也遇到了这个问题，测试项目源码 地址：https://github.com/ChinaZeng/CTest

在 `buildSrc` 工程的 `build.gradle` 的 `dependencies` 中加上：

```gradle
api "com.android.tools.build:gradle:4.0.0"
```

请参考：https://github.com/boostersamples/app/blob/master/buildSrc/build.gradle#L61

**Comment by johnsonlee** [comment]
@svenjung @ChinaZeng  我的锅，文档已更新：https://booster.johnsonlee.io/developer/first-class-transformer.html
