### ISSUE TITLE
pngquant和analyse引入后 跟Dokit冲突

### ISSUE THREAD

**Issue by dxplay120** [didi/booster#202]
booster的pngquant和analyse 引入后 跟Dokit（3.2.0版本）冲突 报这个task已存在的错误

- Gradle version
6.1.1
- Android Gradle plugin version
4.0.1
- Booster version
2.4.0
- Stack traces
![image](https://user-images.githubusercontent.com/4479794/97416208-20469f80-1941-11eb-8cfe-7e8a6c78567a.png)

**Comment by neighbWang** [comment]
名字重复了。两个任务定义了相同的名字。

**Comment by johnsonlee** [comment]
这个问题 DoKit 即将推出的新版本已经解决了，请关注 DoKit 的 Release Notes
