### ISSUE TITLE
apk 打包丢失so文件

### ISSUE THREAD

**Issue by muxi166** [didi/booster#203]
apk 打包后没有lib文件目录

Gradle version
5.1.1
Android Gradle plugin version
3.4.2
Booster version
2.4.0
Stack traces

**Comment by johnsonlee** [comment]
这个问题在 AGP `3.5.3` 上有发现过，能提供 sample 工程吗？

**Comment by neighbWang** [comment]
AGP `3.5.x` 的原生机制，在某些case下会删除so文件，暂时没有在其他版本发现类似问题。

**Comment by muxi166** [comment]
> 这个问题在 AGP `3.5.3` 上有发现过，能提供 sample 工程吗？

我试试booster sample 能不能复现

**Comment by muxi166** [comment]
> AGP `3.5.x` 的原生机制，在某些case下会删除so文件，暂时没有在其他版本发现类似问题。

升级到3.5.1 可以正常打包，但是项目目前无法升级；3.4.2 下 org.gradle.caching改成false 才可以正常打包

**Comment by neighbWang** [comment]
你命中cache了。 `org.gradle.caching=false` 将cache关闭了。你可以在3.4.2按照`./gradlew clean :app:assembleXXX --no-build-cache`命令进行构建看看APK中是否存在相应的so文件。如果方便的话，提供一个sample 工程也可以。

**Comment by muxi166** [comment]
> 你命中cache了。 `org.gradle.caching=false` 将cache关闭了。你可以在3.4.2按照`./gradlew clean :app:assembleXXX --no-build-cache`命令进行构建看看APK中是否存在相应的so文件。如果方便的话，提供一个sample 工程也可以。

--no-build-cache 跟 org.gradle.caching=false 一样， apk里有相应的so

**Comment by muxi166** [comment]
> > 你命中cache了。 `org.gradle.caching=false` 将cache关闭了。你可以在3.4.2按照`./gradlew clean :app:assembleXXX --no-build-cache`命令进行构建看看APK中是否存在相应的so文件。如果方便的话，提供一个sample 工程也可以。
> 
> --no-build-cache 跟 org.gradle.caching=false 一样， apk里有相应的so。 demo 有空弄一个

关闭cache 挺影响开发效率的

**Comment by muxi166** [comment]
@johnsonlee 已经修复了？

**Comment by johnsonlee** [comment]
这个是 AGP 的 bug，已经超出了 booster 的 scope

**Comment by FutureHere** [comment]
> @johnsonlee 已经修复了？

请问是否解决 遇到同样问题
