### ISSUE TITLE
Windows 10 编译失败

### ISSUE THREAD

**Issue by knclj** [didi/booster#204]
Please provide the following informations.

- System version Windows 10

- Java version java 8

- Gradle version 5.1

- Android Gradle plugin version 3.4.1

- Booster version 2.4.0

- Stack traces

编译失败提示:

drawable-xxxhdp-v4_image_xxx.png.flat:error:failed to open file
Comand 'F:\xxx\xxx\build-tools\28.0.3\appt2.exe' compile -o 'F:\xxx\xxx\app\build\imtermediates\res\merged\xxx\debug' 
'F:\xxx\xxx\app\build\intermediates\compressed_res_pngquant\xxx\debug\compressxxxDebugResourceWithPngquant\drawable-xxxhdpi-v4\image_xxx.png' exited with no-zero value 0.

**Comment by johnsonlee** [comment]
清理一下缓存试试？

**Comment by johnsonlee** [comment]
如果可以的话，麻烦提供一个 sample 工程，我们复现一下

**Comment by llong0807** [comment]
> 如果可以的话，麻烦提供一个 sample 工程，我们复现一下

有解决方案吗
