### ISSUE TITLE
如何发现潜在的性能问题

### ISSUE THREAD

**Issue by weimuhua** [didi/booster#21]
使用 Booster 可以发现潜在的性能问题，例如，在应用中调用可能阻塞 UI 线程或者主线程的 API，如：I/O API

在wiki里的介绍发现了这样的一段介绍。目前我在代码中只发现了，利用transform把sp的commit方法移到非UI线程，想了解关于性能这一块，后续是否还有其他的实现？

**Comment by johnsonlee** [comment]
https://github.com/didi/booster/blob/master/booster-transform-lint/README.md
