### ISSUE TITLE
A problem occurred configuring project ':app'. > Cannot change dependencies of dependency configuration ':app:implementation' after it has been included in dependency resolution.

### ISSUE THREAD

**Issue by JoeMmmmm** [didi/booster#219]
Please provide the following informations.

- System version

- Java version

- Gradle version 6.1

- Android Gradle plugin version 4.0.0

- Booster version 3.0.0

A problem occurred configuring project ':app'.
> Cannot change dependencies of dependency configuration ':app:implementation' after it has been included in dependency resolution.

**Comment by JoeMmmmm** [comment]
集成toast插件的时候远程依赖报错如上
将插件逻辑放到本地buildSrc同样报错如上
麻烦同步下原因😭

**Comment by johnsonlee** [comment]
有同时使用其它的插件么？
