### ISSUE TITLE
Some thoughts about the graph of method invocation

### ISSUE THREAD

**Issue by amylovesong** [didi/booster#22]
I saw the follow graph in a presentation of booster, I think it's too messy to understand. How about vertical layout for it? In that way the lines between the method blocks will be shorter and the hierarchy cleaner.
Just a little suggestion~ 😊
![image](https://user-images.githubusercontent.com/5869969/58066371-aa6ece00-7bbb-11e9-9cf0-d2b842a58a80.png)

**Comment by johnsonlee** [comment]
Thanks for your suggestions! Maybe you're right, if the call stack deep enough, the graph would be too  wide to read, and TOP-DOWN layout is more suitable for call stack presenting

**Comment by amylovesong** [comment]
> Thanks for your suggestions! Maybe you're right, if the call stack deep enough, the graph would be too wide to read, and TOP-DOWN layout is more suitable for call stack presenting

Yes, that's what I mean. 😊
