### ISSUE TITLE
请问bootser针对线程具体是怎么优化的

### ISSUE THREAD

**Issue by geakw** [didi/booster#24]
如题

**Comment by johnsonlee** [comment]
主要是两部分：

- 线程池的参数优化
- 线程重命名

详见代码：https://github.com/didi/booster/blob/master/booster-transform-thread

**Comment by duanxifeng** [comment]
集成后dump存活的线程名称，没有显示ShadowThread等字样，不确定是否生效了

**Comment by johnsonlee** [comment]
> 集成后dump存活的线程名称，没有显示ShadowThread等字样，不确定是否生效了

理解有误，线程重命名在原来的 *name* 的基础上加上前缀——*创建该线程的类的全类名*

**Comment by Kyson** [comment]
@johnsonlee 线程优化不会把thread替换为ShadowThread吗

**Comment by johnsonlee** [comment]
> @johnsonlee 线程优化不会把thread替换为ShadowThread吗

v2.3.0 之前的版本是不会替换成  `ShadowThread`
v2.3.0 之后的版本才会被替换成 `ShadowThread`

**Comment by Kyson** [comment]
> > @johnsonlee 线程优化不会把thread替换为ShadowThread吗
> 
> v2.3.0 之前的版本是不会替换成 `ShadowThread`
> v2.3.0 之后的版本才会被替换成 `ShadowThread`

大佬，我这边写了个demo测试了一下，有两个问题

1. 对于如下继承thread的情况，命名重复了，在new指令的时候会给thread命名，在thread构造函数中又给thread命名了

```
public static class SubThread extends Thread {
        public SubThread() {
            super("​com.xunmeng.pinduoduo.appinit.testcase.testthread.ThreadTestCase$SubThread");
        }
    }

ShadowThread.setThreadName(new SubThread(), str3).start();
```

对于继承ThreadPool的情况，线程的优化也失效了

```
    public static class SubThreadPoolExecutor extends ThreadPoolExecutor {
        public SubThreadPoolExecutor(int corePoolSize, int maximumPoolSize, long keepAliveTime, TimeUnit unit, BlockingQueue<Runnable> workQueue) {
            super(corePoolSize, maximumPoolSize, keepAliveTime, unit, workQueue, NamedThreadFactory.newInstance("​com.xunmeng.pinduoduo.appinit.testcase.testthread.ThreadTestCase$SubThreadPoolExecutor"));
        }
    }

new SubThreadPoolExecutor(2, 2, 0, TimeUnit.MILLISECONDS, new LinkedBlockingQueue()).execute(new Runnable() {
            public void run() {
            }
        });
```

![image](https://user-images.githubusercontent.com/3901140/105623970-fa09a080-5e58-11eb-96e2-c7ab72426d6b.png)

求解答 @johnsonlee

**Comment by Kyson** [comment]
SubThreadPoolExecutor的继承关系没有换成shadow的，new的时候也没有替换

**Comment by johnsonlee** [comment]
1. 会出现多个地方重命名，构造方法以外的重命名调用是为了兜底，在名字里会有一个标记，如果被重命名过，即使再重命名也不会有变化
2. 自定义 `ThreadPoolExecutor` 的处理方式跟 `Thread` 的处理方式一样，可能文档没有更新，从 `v2.3.0` 开始，线程优化的实现跟之前有所区别了

**Comment by Kyson** [comment]
@johnsonlee 多谢大佬解答
