### ISSUE TITLE
Execution failed for task ':app:analyseRelease'. java.util.concurrent.ExecutionException: java.io.FileNotFoundException: xxxx.xml (No such file or directory)

### ISSUE THREAD

**Issue by allenhsu-17live** [didi/booster#243]
Please provide the following informations.

- System version

- Java version
JDK 1.8

- Gradle version
- 6.5.1

- Android Gradle plugin version
4.2.2
- Booster version
3.3.1
- Stack traces

```
Execution failed for task ':app:analyseRelease'.
> java.util.concurrent.ExecutionException: java.io.FileNotFoundException: xxxx.xml (No such file or directory)
```

但xxx.xml layout檔明顯存在

**Comment by allenhsu-17live** [comment]
而且沒有  ./gradlew analyseDebug的gradle job

**Comment by johnsonlee** [comment]
The analysis task has been changed dramatically
