### ISSUE TITLE
KotlinDependencyExtensionsKt 找不到

### ISSUE THREAD

**Issue by 1982582704** [didi/booster#276]
下载，导入项目之后报
import static org.gradle.kotlin.dsl.KotlinDependencyExtensionsKt.embeddedKotlinVersion
中的  KotlinDependencyExtensionsKt 找不到。
![1111](https://user-images.githubusercontent.com/17525427/148024997-67342afb-0169-4120-9217-519a57f78c59.jpg)

**Comment by johnsonlee** [comment]
IDE's problem
