### ISSUE TITLE
Could not find booster-task-resource-deredundancy.jar

### ISSUE THREAD

**Issue by 1982582704** [didi/booster#277]
Please provide the following informations.

- System version win10

- Java version 1.8.0_60

- Gradle version  gradle-5.4.1-all.zip

- Android Gradle plugin version  com.android.tools.build:gradle:3.5.0

- Booster version  4.3.0

- Stack traces

Could not resolve all artifacts for configuration ':classpath'.
   > Could not find booster-task-resource-deredundancy.jar (com.didiglobal.booster:booster-task-resource-deredundancy:4.3.0).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/com/didiglobal/booster/booster-task-resource-deredundancy/4.3.0/booster-task-resource-deredundancy-4.3.0.jar
   > Could not find booster-aapt2.jar (com.didiglobal.booster:booster-aapt2:4.3.0).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/com/didiglobal/booster/booster-aapt2/4.3.0/booster-aapt2-4.3.0.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

![222](https://user-images.githubusercontent.com/17525427/148037470-ad4ecbdd-05f7-4b62-b779-5789453b41e0.jpg)

**Comment by johnsonlee** [comment]
please use `mavenCentral()`
