### ISSUE TITLE
booster-transform-activity-thread 依赖

### ISSUE THREAD

**Issue by 1982582704** [didi/booster#279]
Please provide the following informations.

- System version win10

- Java version 1.8

- Gradle version gradle-5.4.1-all.zip

- Android Gradle plugin version 3.5.0

- Booster version 3.4.0

- Stack traces
-  classpath "com.didiglobal.booster:booster-transform-activity-thread:$booster_version"
提示：
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find booster-transform-activity-thread.jar (com.didiglobal.booster:booster-transform-activity-thread:4.3.0).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/com/didiglobal/booster/booster-transform-activity-thread/4.3.0/booster-transform-activity-thread-4.3.0.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

![1641457628(1)](https://user-images.githubusercontent.com/17525427/148352701-87b9b14b-c5ec-469b-bc59-0e0dbd0049d5.jpg)

**Comment by 1982582704** [comment]
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find booster-transform-res-check.jar (com.didiglobal.booster:booster-transform-res-check:4.3.0).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/com/didiglobal/booster/booster-transform-res-check/4.3.0/booster-transform-res-check-4.3.0.jar
   > Could not find booster-transform-toast.jar (com.didiglobal.booster:booster-transform-toast:4.3.0).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/com/didiglobal/booster/booster-transform-toast/4.3.0/booster-transform-toast-4.3.0.jar
   > Could not find booster-transform-activity-thread.jar (com.didiglobal.booster:booster-transform-activity-thread:4.3.0).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/com/didiglobal/booster/booster-transform-activity-thread/4.3.0/booster-transform-activity-thread-4.3.0.jar
   > Could not find booster-task-compression-cwebp.jar (com.didiglobal.booster:booster-task-compression-cwebp:4.3.0).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/com/didiglobal/booster/booster-task-compression-cwebp/4.3.0/booster-task-compression-cwebp-4.3.0.jar

**Comment by ff-frida** [comment]
> Please provide the following informations.
> 
> * System version win10
> * Java version 1.8
> * Gradle version gradle-5.4.1-all.zip
> * Android Gradle plugin version 3.5.0
> * Booster version 3.4.0
> * Stack traces
> * classpath "com.didiglobal.booster:booster-transform-activity-thread:$booster_version"
>   提示：
>   A problem occurred configuring root project 'android'.
> 
> > Could not resolve all artifacts for configuration ':classpath'.
> > Could not find booster-transform-activity-thread.jar (com.didiglobal.booster:booster-transform-activity-thread:4.3.0).
> > Searched in the following locations:
> > https://maven.aliyun.com/repository/jcenter/com/didiglobal/booster/booster-transform-activity-thread/4.3.0/booster-transform-activity-thread-4.3.0.jar
> 
> Possible solution:
> 
> * Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
> 
> ![1641457628(1)](https://user-images.githubusercontent.com/17525427/148352701-87b9b14b-c5ec-469b-bc59-0e0dbd0049d5.jpg)

repositories使用google()
        jcenter()
        mavenCentral()，我是可以正常拿到的。

**Comment by johnsonlee** [comment]
aliyun 的 maven 镜像问题
