### ISSUE TITLE
AGP7有一个功能不能使用

### ISSUE THREAD

**Issue by liukai2530533** [didi/booster#284]
Please provide the following informations.

- System version 12

- Java version 1.8

- Gradle version 7.0.2

- Android Gradle plugin version 7.0.3

- Booster version 4.4.0

- Stack traces
- > Task :app:processReleaseResources FAILED

Execution failed for task ':app:processReleaseResources'.
> Querying the mapped value of property(org.gradle.api.file.Directory, property(org.gradle.api.file.Directory, property(org.gradle.api.file.Directory, map(org.gradle.api.file.Directory flatmap(provider(task 'processReleaseResources', class com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask)) check-type())))) before task ':app:processReleaseResources' has completed is not supported

只是这个任务失败了，我只有把这个任务注释掉就能正常使用其他的功能
 //classpath "com.didiglobal.booster:booster-task-compression-processed-res:$booster_version"  //无法使用这个功能
 大佬看看什么问题

**Comment by nichbar** [comment]
Task `booster-transform-br-inline:$booster_version` share the same error.

**Comment by johnsonlee** [comment]
Fixed in `v4.5.2`
