### ISSUE TITLE
无法成功集成

### ISSUE THREAD

**Issue by HeartNeverDie** [didi/booster#30]
Could not GET 'https://dl.google.com/dl/android/maven2/com/didiglobal/booster/booster-gradle-plugin/0.4.4/booster-gradle-plugin-0.4.4.pom'. Received status code 400 from server: Bad Request
![image](https://user-images.githubusercontent.com/33239884/58390006-83a01400-8061-11e9-9e75-39c058e4fd81.png)

**Comment by HeartNeverDie** [comment]
没有设置过代理
![image](https://user-images.githubusercontent.com/33239884/58390112-23f63880-8062-11e9-8600-2a508460bf23.png)

**Comment by HeartNeverDie** [comment]
已解决..打扰了

**Comment by pie-tk** [comment]
是什么问题
