### ISSUE TITLE
About Standalone Transformer

### ISSUE THREAD

**Issue by Muchenyao** [didi/booster#302]
按照demo，我在buildSrc创建了一个插件，

```kotlin
@AutoService(ClassTransformer::class)
class CatchBundleClassNotFound :ClassTransformer {

  override fun transform(context: TransformContext, klass: ClassNode): ClassNode {
    println("Transforming ${klass.name}")
    return klass
  }

}
```

构建过程中查看日志，只扫描自己的类，没有第三方库的类。

查看文档https://booster.johnsonlee.io/en/developer/standalone-transformer.html#runtime-instrumentation ，似乎是可以对第三方aar中的class做修改的。 

请问这个过程是需要自定义gradle task 来处理第三方class吗？

如果有这个过程的demo就更好了。

**Comment by neighbWang** [comment]
可以参照[samples](https://github.com/boostersamples)试试

**Comment by Muchenyao** [comment]
感谢，在app/ 下找到了相关示例
