### ISSUE TITLE
请问加了之后，正常编译，启动GreenDao报could not init DAOConfig

### ISSUE THREAD

**Issue by hyr0318** [didi/booster#31]
没用booster，GreenDao初始化正常

**Comment by johnsonlee** [comment]
请参考：https://github.com/didi/booster/blob/master/booster-transform-shrink，将 `greendao` 相关的类忽略

**Comment by johnsonlee** [comment]
麻烦提供一下堆栈信息以便于我们持续优化和改进

**Comment by hyr0318** [comment]
> 麻烦提供一下堆栈信息以便于我们持续优化和改进

请问是哪一部分？ GreenDao报错的那里吗？

**Comment by johnsonlee** [comment]
> > 麻烦提供一下堆栈信息以便于我们持续优化和改进
> 
> 请问是哪一部分？ GreenDao报错的那里吗？

对的

**Comment by johnsonlee** [comment]
请问你们项目中引用的 `greendao` 是什么版本？是官方的 `org.greenrobot:greendao:${greendao_version}` 么？

**Comment by hyr0318** [comment]
> > > 麻烦提供一下堆栈信息以便于我们持续优化和改进
> > 
> > 
> > 请问是哪一部分？ GreenDao报错的那里吗？
> 
> 对的

好的。

和GreenDao相关的报错:
2019-05-27 11:05:44.554 I: Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/sqlcipher/database/SQLiteOpenHelper;

Caused by: java.lang.ClassNotFoundException: Didn't find class "net.sqlcipher.database.SQLiteOpenHelper" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xiaobu121.xiaobu.xiaobu_android-E-uSm41qIn4RmfUNC1WEAQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.xiaobu121.xiaobu.xiaobu_android-E-uSm41qIn4RmfUNC1WEAQ==/lib/arm, /data/app/com.xiaobu121.xiaobu.xiaobu_android-E-uSm41qIn4RmfUNC1WEAQ==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]
2019-05-27 11:05:44.555 I:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
2019-05-27 11:05:44.555 I:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2019-05-27 11:05:44.555 I:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)

**Comment by hyr0318** [comment]
> 请问你们项目中引用的 `greendao` 是什么版本？是官方的 `org.greenrobot:greendao:${greendao_version}` 么？

是官方的，用的是3.0.1 我试了更新最新的3.2.2 也报错

**Comment by johnsonlee** [comment]
试试先把 `booster-transform-shrink` 模块去掉，单独引用其它的模块：

```groovy
dependencies {
    classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
    classpath "com.didiglobal.booster:booster-task-all:$booster_version"
//    classpath "com.didiglobal.booster:booster-transform-all:$booster_version"
    classpath "com.didiglobal.booster:booster-transform-lint:$booster_version"
    classpath "com.didiglobal.booster:booster-transform-shared-preferences:$booster_version"
    classpath "com.didiglobal.booster:booster-transform-thread:$booster_version"
    classpath "com.didiglobal.booster:booster-transform-toast:$booster_version"
}
```

**Comment by hyr0318** [comment]
去掉 booster-transform-shrink 模块 可以正常运行了。那如果在一个已经上线的项目中加入booster 是不是会有风险的额？

**Comment by johnsonlee** [comment]
集成 Booster 后需要做回归测试

**Comment by hyr0318** [comment]
> 集成 Booster 后需要做回归测试

好的。

每次发版打包的apk 需要用 ./gradlew assembleRelease 构建的包 然后再签名 加固么？

**Comment by johnsonlee** [comment]
> > 集成 Booster 后需要做回归测试
> 
> 好的。
> 
> 每次发版打包的apk 需要用 ./gradlew assembleRelease 构建的包 然后再签名 加固么？

正常流程是这样

**Comment by hyr0318** [comment]
> > > 集成 Booster 后需要做回归测试
> > 
> > 
> > 好的。
> > 每次发版打包的apk 需要用 ./gradlew assembleRelease 构建的包 然后再签名 加固么？
> 
> 正常流程是这样

java版本有限制的嘛？

* What went wrong:
Could not determine java version from '12'.

**Comment by johnsonlee** [comment]
推荐用 Java 8

**Comment by hyr0318** [comment]
> JDK 推荐用 Java 8，关于 `sourceCompatibility` 和 `targetCompatibility` 推荐：
> 
> ```groovy
> sourceCompatibility = JavaVersion.VERSION_1_7
> targetCompatibility = JavaVersion.VERSION_1_7
> ```

sourceCompatibility 和 targetCompatibility  我们项目好像得需要用VERSION_1_8 。用VERSION_1_8 就用不了booster 嘛？

**Comment by johnsonlee** [comment]
> > JDK 推荐用 Java 8，关于 `sourceCompatibility` 和 `targetCompatibility` 推荐：
> > ```groovy
> > sourceCompatibility = JavaVersion.VERSION_1_7
> > targetCompatibility = JavaVersion.VERSION_1_7
> > ```
> 
> sourceCompatibility 和 targetCompatibility 我们项目好像得需要用VERSION_1_8 。用VERSION_1_8 就用不了booster 嘛？

`VERSION_1_8` 也能用，可能会遇到 `Java 8` 语法导致的编译问题，如：#20

**Comment by hyr0318** [comment]
> > > JDK 推荐用 Java 8，关于 `sourceCompatibility` 和 `targetCompatibility` 推荐：
> > > ```groovy
> > > sourceCompatibility = JavaVersion.VERSION_1_7
> > > targetCompatibility = JavaVersion.VERSION_1_7
> > > ```
> > 
> > 
> > sourceCompatibility 和 targetCompatibility 我们项目好像得需要用VERSION_1_8 。用VERSION_1_8 就用不了booster 嘛？
> 
> `VERSION_1_8` 也能用，可能会遇到 _Java 8_ 语法导致的编译问题，如：#20

sdk更换成java1.8 可以正常打包。但是更换成JavaVersion.VERSION_1_7 项目中原来使用rxjava的地方都报错，没法换成JavaVersion.VERSION_1_7 哎。使用JavaVersion.VERSION_1_8，能正常编译运行。另外这个GreenDao 的问题 需要怎么解决？ 目前只能通过不使用booster-transform-shrink 模块解决么？

**Comment by johnsonlee** [comment]
`greendao` 的问题还需要提供更多的堆栈信息来帮助我们定位问题，如果能提供一个 sample 工程就更好了

**Comment by hyr0318** [comment]
我把GreenDao相关的提取到新项目中，又能正常初始化。。。

**Comment by hyr0318** [comment]
我把GreenDao相关的提取到新项目中，又能正常初始化。。。但是在原来的项目中就 始终不能初始化，不要Booster 就正常。。

**Comment by johnsonlee** [comment]
please try the latest version `0.23.0-SNAPSHOT` or `0.23.0`
