### ISSUE TITLE
编译失败Unable to find method ''java.util.Collection com.didiglobal.booster.gradle.BaseVariantKt.getMergedManifests

### ISSUE THREAD

**Issue by fuxuanyang11** [didi/booster#330]
Please provide the following informations.

- System version win10

- Java version 11

- Gradle version 7.2

- Android Gradle plugin version 7.1.2

- Booster version 4.9.0

- Stack traces
Unable to find method ''java.util.Collection com.didiglobal.booster.gradle.BaseVariantKt.getMergedManifests(com.android.build.gradle.api.BaseVariant)''
'java.util.Collection com.didiglobal.booster.gradle.BaseVariantKt.getMergedManifests(com.android.build.gradle.api.BaseVariant)'

**Comment by johnsonlee** [comment]
4.9.0 之后这个 API 的返回值类型变成 `FileCollection` 了

请问你是在项目里调用了 Booster API 么？
