### ISSUE TITLE
dex包编译耗时问题

### ISSUE THREAD

**Issue by lavender1626** [didi/booster#331]
编译时AGPBI一直在刷warning 是打包时间里最久的，耗时23秒，总共360条记录，一直在找这个文件
![image](https://user-images.githubusercontent.com/22656300/170688165-0ab2e621-cfcf-4413-a731-d6960a4c61ab.png)
请问是否有方法可以解决此问题

**Comment by johnsonlee** [comment]
跑一下 profiling
