### ISSUE TITLE
compressDebugResourcesWithPngquant 任务执行报 exited with non-zero value 98 异常

### ISSUE THREAD

**Issue by hewking** [didi/booster#336]
Please provide the following informations.

- System version ： win0

- Java version： jdk 14

- Gradle version: 6.1.1

- Android Gradle plugin version: 4.0.1

- Booster version: 4.9.0

- Stack traces:  Task ':app:compressDebugResourcesWithPngquant' is not up-to-date because:
  Task has failed previously.
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-xhdpi-v4\abc_text_select_handle_right_mtrl.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-xhdpi-v4\abc_text_select_handle_right_mtrl.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-mdpi-v4\abc_btn_check_to_on_mtrl_015.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-mdpi-v4\abc_btn_check_to_on_mtrl_015.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-xxhdpi-v4\abc_scrubber_control_off_mtrl_alpha.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-xxhdpi-v4\abc_scrubber_control_off_mtrl_alpha.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-xhdpi-v4\abc_btn_radio_to_on_mtrl_015.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-xhdpi-v4\abc_btn_radio_to_on_mtrl_015.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-mdpi-v4\abc_text_select_handle_left_mtrl.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-mdpi-v4\abc_text_select_handle_left_mtrl.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-xxxhdpi-v4\abc_scrubber_control_to_pressed_mtrl_005.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-xxxhdpi-v4\abc_scrubber_control_to_pressed_mtrl_005.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-hdpi-v4\abc_scrubber_control_to_pressed_mtrl_005.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-hdpi-v4\abc_scrubber_control_to_pressed_mtrl_005.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-hdpi-v4\notify_panel_notification_icon_bg.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\c45db057bf0d2e27848fae9a8c0e9189\core-1.5.0\res\drawable-hdpi-v4\notify_panel_notification_icon_bg.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-hdpi-v4\abc_btn_check_to_on_mtrl_000.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-hdpi-v4\abc_btn_check_to_on_mtrl_000.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-xxhdpi-v4\abc_text_select_handle_middle_mtrl.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-xxhdpi-v4\abc_text_select_handle_middle_mtrl.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-xxhdpi-v4\abc_btn_check_to_on_mtrl_015.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-xxhdpi-v4\abc_btn_check_to_on_mtrl_015.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-hdpi-v4\abc_btn_radio_to_on_mtrl_015.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-hdpi-v4\abc_btn_radio_to_on_mtrl_015.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-xhdpi-v4\abc_scrubber_control_to_pressed_mtrl_000.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-xhdpi-v4\abc_scrubber_control_to_pressed_mtrl_000.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-mdpi-v4\abc_ic_commit_search_api_mtrl_alpha.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-mdpi-v4\abc_ic_commit_search_api_mtrl_alpha.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-xxxhdpi-v4\abc_btn_check_to_on_mtrl_015.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-xxxhdpi-v4\abc_btn_check_to_on_mtrl_015.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-hdpi-v4\abc_ic_commit_search_api_mtrl_alpha.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-hdpi-v4\abc_ic_commit_search_api_mtrl_alpha.png` exited with non-zero value 98
Command `E:\fcbox\fclib\networkApm\app\build\bin\pngquant.exe --strip --skip-if-larger -f -o E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-xxhdpi-v4\abc_btn_radio_to_on_mtrl_000.png -s 3 -Q 80-100 C:\Users\003710\.gradle\caches\transforms-2\files-2.1\98a1de973d5993383dc5bebbe4f2d39a\appcompat-1.3.0\res\drawable-xxhdpi-v4\abc_btn_radio_to_on_mtrl_000.png` exited with non-zero value 98
Command `D:\Android\Sdk\build-tools\29.0.2\aapt2.exe compile -o E:\fcbox\fclib\networkApm\app\build\intermediates\res\merged\debug E:\fcbox\fclib\networkApm\app\build\intermediates\compressed_res_pngquant\debug\compressDebugResourcesWithPngquant\drawable-mdpi\ic_launcher_background.png` exited with non-zero value 0

**Comment by johnsonlee** [comment]
正常 case，error code `98`: 压缩后的 size 比压缩前更大，所以放弃压缩结果了

**Comment by hewking** [comment]
> 正常 case，error code `98`: 压缩后的 size 比压缩前更大，所以放弃压缩结果了
大佬压缩后比压缩前还大这种情况是怎样出现的呢

**Comment by johnsonlee** [comment]
Please refer to [pngquant](https://pngquant.org/)
