### ISSUE TITLE
booster-task-analyser作用是什么？

### ISSUE THREAD

**Issue by ckrgithub** [didi/booster#337]
生成了.dot文件，然后干嘛用（或者结合什么一起分析）

**Comment by johnsonlee** [comment]
see [README](https://github.com/didi/booster/blob/master/booster-task-analyser/README.md)

**Comment by ckrgithub** [comment]
@johnsonlee .dot文件并生成了png文件，但我还是领会不了，这些文件作用(使用场景)

**Comment by johnsonlee** [comment]
DAG (Directed Acyclic Graph) Visualization
