### ISSUE TITLE
自定义ClassTransformer要获取自定义的extensions要怎么做？

### ISSUE THREAD

**Issue by CCtomorrow** [didi/booster#339]
Please provide the following informations.

- System version
win 10
- Java version
jdk 8
- Gradle version
6.1.1
- Android Gradle plugin version
4.0.0
- Booster version
4.9.0
- Stack traces

自定义的ClassTransformer参数TransformContext获取不到ExtensionContainer，要实现能获取自定义extension的ClassTransformer需要怎么做？

**Comment by johnsonlee** [comment]
可以在 `VariantProcessor` 里获取，`ClassTransformer` 不支持直接访问 Gradle API

**Comment by CCtomorrow** [comment]
ok，之前看说明也是可以在`VariantProcessor`里面获取，但是自己的需求又用不上`VariantProcessor`，所以就想着来问问
