### ISSUE TITLE
集成后 编译不过~

### ISSUE THREAD

**Issue by joker-fu** [didi/booster#35]
An operation is not implemented: Reducing redundant resources without aapt2 enabled has not supported yet

**Comment by johnsonlee** [comment]
`aapt v1` 官方已经废弃了，所以，Booster 暂时不打算支持

**Comment by dany1202happy** [comment]
android.enableAapt2=true
check gradle.properties,如果被设置了flase会提示这个log

**Comment by johnsonlee** [comment]
> android.enableAapt2=true
> check gradle.properties,如果被设置了flase会提示这个log

建议升级 Android gradle plugin 版本到 3.2.0+
