### ISSUE TITLE
请问下 BoosterSharedPreforences被应用在滴滴出行的哪个版本？

### ISSUE THREAD

**Issue by tuke0919** [didi/booster#354]
Please provide the following informations.

- System version

- Java version

- Gradle version

- Android Gradle plugin version

- Booster version

- Stack traces

**Comment by neighbWang** [comment]
Sp优化暂时先别用了，后续会有新的重构。重构后在使用吧。

**Comment by neighbWang** [comment]
已回复您发送的邮件，所以关闭该issue。
