### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by zhuangzhitu** [didi/booster#360]
AGP 8.0 会废弃Transform API，到时候打算怎么适配呢？

**Comment by neighbWang** [comment]
Booster 之前对API抽象了一层，底层是用 AGP 的 Transform API 还是 Gradle 的 TransformAction ，开发者并不需要关心，能正确 使用Booster APi 就行了。
其实个人理解8.0还好， 9.0是变化很大的一个版本。

**Comment by neighbWang** [comment]
后续Booster有个大版本更新，会进行全面适配新的能力，尽量让用户无感知升级。

**Comment by zhuangzhitu** [comment]
嗯。说错了，AGP 9.0 会直接去掉 Transform API ，但是API 变化挺大的，整个都会影响到。

**Comment by neighbWang** [comment]
Booster后面会适配的。新启一个大版本。

**Comment by zhuangzhitu** [comment]
OK

**Comment by sickworm** [comment]
> 

查了一下，是7.0废弃，8.0移除

**Comment by sickworm** [comment]
> 嗯。说错了，AGP 9.0 会直接去掉 Transform API ，但是API 变化挺大的，整个都会影响到。

查了一下，是7.0废弃，8.0移除
