### ISSUE TITLE
4.12.0 Transformer 不生效

### ISSUE THREAD

**Issue by sw926** [didi/booster#364]
使用 Android Studio 新建空白项目，agp 版本号 7.2.2，根据文档写了一个 FirstClassTransformer 发布到了 MavenLocal，使用 booster 4.12.0 时 FirstClassTransformer 没有生效，修改为 4.11.0 生效了。

**Comment by punkisnotdead3** [comment]
我也有一样的问题，我本地复现了看看 能不能修复一下

**Comment by wangwei66666** [comment]
我也遇到了一样的问题，在新版android studio中无法使用booster-transform-thread

**Comment by johnsonlee** [comment]
fixed in #367
