### ISSUE TITLE
使用cwebp和pngquant遇到问题

### ISSUE THREAD

**Issue by healthyxth** [didi/booster#378]
我想通过booster-task-compression-cwebp和booster-task-compression-pngquant来压缩第三方SDK的图片，但是遇到以下的问题

1、使用pngquant会报以下错误：
```
Execution failed for task ':switchbot-app:compressPrdReleaseResourcesWithPngquant'.
> Process 'command '/Users/switchbot/Library/Android/sdk/build-tools/30.0.3/aapt2'' finished with non-zero exit value 1
```

2、使用cwebp有时可以将第三方SDK的图片转换成webp，有时不行。后面将org.gradle.parallel设置为false后才可以每次都将第三方SDK的图片转换成webp，但是这样打包时间耗时太长了。

下面是我的开发环境
系统：MacOs 12.5.1 M1芯片
AGP：7.0.0
Gradle：7.1

期望能得到你们的回复。

**Comment by fredzzt** [comment]
classpath "io.johnsonlee.booster:booster-pngquant-provider:2.3.0"

**Comment by neighbWang** [comment]
实在抱歉。
1. `Pngquant` 版本已经适配`M1`，但是没有发布正式版~
2. `Webp` 的转换是使用官方工具，应该也没有适配M1版本，这两周会一起适配。不过这个不确定能解决配置的问题。如果仍有问题，可以尝试在`Debug`/本地开发模式下关闭图片压缩能力，节约打包时间。

**Comment by johnsonlee** [comment]
alternatively, installing local `pngquant` or `cwebp` is also supported by Booster
