### ISSUE TITLE
编译时候报错Broken class: 21.jar!/org/bouncycastle/LICENSE.class

### ISSUE THREAD

**Issue by lexluthors** [didi/booster#382]
org/bouncycastle整个包下面的文件都没有编译打包进去。导致运行的时候报错找不到类。
fun ZipFile.transform(
        output: OutputStream,
        entryFactory: (ZipEntry) -> ZipArchiveEntry = ::ZipArchiveEntry,
        transformer: (ByteArray) -> ByteArray = { it -> it }
) {
    val entries = mutableSetOf<String>()
    val creator = ParallelScatterZipCreator(ThreadPoolExecutor(NCPU, NCPU, 0L, TimeUnit.MILLISECONDS, LinkedBlockingQueue<Runnable>(), Executors.defaultThreadFactory(), RejectedExecutionHandler { runnable, _ ->
        runnable.run()
    }))

    entries().asSequence().forEach { entry ->
        if (!entries.contains(entry.name)) {
            val zae = entryFactory(entry)
            val stream = InputStreamSupplier {
                when (entry.name.substringAfterLast('.', "")) {
                    "class" -> getInputStream(entry).use { src ->
                        try {
                            src.transform(transformer).inputStream()
                        } catch (e: Throwable) {
                            System.err.println("Broken class: ${this.name}!/${entry.name}")
                            getInputStream(entry)
                        }
                    }
                    else -> getInputStream(entry)
                }
            }

            creator.addArchiveEntry(zae, stream)
            entries.add(entry.name)
        } else {
            System.err.println("Duplicated jar entry: ${this.name}!/${entry.name}")
        }
    }

    ZipArchiveOutputStream(output).use(creator::writeTo)
}

在这个函数里抛出的异常。使用的依赖库是： implementation "org.bouncycastle:bcprov-jdk15on:1.56"
这个库始终无法打包进去。希望能收到回复。谢谢。

**Comment by johnsonlee** [comment]
Duplication of #368 

Already been fixed, please upgrade to `4.13.0` and above

**Comment by kuyu132** [comment]
@johnsonlee 这个问题在4.16.3版本上又出现了，agp为7.4.2版本

**Comment by johnsonlee** [comment]
用了啥别的Gradle插件？把booster放到最前面试试

**Comment by kuyu132** [comment]
> 用了啥别的Gradle插件？把booster放到最前面试试

我的部分配置如下，怀疑可能是ARouter造成的，但移动到arouter之前还是有问题。

项目的build.gradle:
dependencies {
    classpath "com.android.tools.build:gradle:$agp_version"
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    // ksp - 加快kotlin编译速度
    classpath 'com.google.devtools.ksp:symbol-processing-api:1.9.10-1.0.13'
    classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
    classpath "com.didiglobal.booster:booster-transform-thread:$booster_version"
    // fcm
    classpath 'com.google.gms:google-services:4.4.1'
    // Add the dependency for the Crashlytics Gradle plugin
    classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
    // Add the dependency for the Performance Monitoring Gradle plugin
    classpath 'com.google.firebase:perf-plugin:1.4.2'
    // hms，若不集成华为厂商通道，可直接跳过
    classpath 'com.huawei.agconnect:agcp:1.6.0.300'
    classpath "com.github.jadepeakpoet.ARouter:arouter-register:$arouter_register_version"
    //The latest version is 0.9.1. It requires at least Gradle 5.6 and Java 8
    classpath 'com.google.protobuf:protobuf-gradle-plugin:0.9.1'
    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files

    classpath('com.facebook.react:react-native-gradle-plugin')
}

allprojects {
    configurations.configureEach {
        def versions = "1.1.0-rc01"
        resolutionStrategy.force "androidx.camera:camera-core:$versions"
        resolutionStrategy.force "androidx.camera:camera-camera2:$versions"
        resolutionStrategy.force "androidx.camera:camera-view:$versions"
        resolutionStrategy.force "androidx.camera:camera-lifecycle:$versions"

        // 【fix 3 issues were found when checking AAR metadata】
        resolutionStrategy.force "androidx.activity:activity:1.5.0"
        // 【fix 类文件具有错误的版本 61.0（17）, 应为 52.0（8）】
        resolutionStrategy.force "com.facebook.react:react-android:0.72.4"
        resolutionStrategy.force "com.facebook.soloader:soloader:0.10.5"
        resolutionStrategy.force "org.bouncycastle:bcpkix-jdk15on:1.670"
        resolutionStrategy.force "org.bouncycastle:bcpkix-jdk15on:1.68"
        resolutionStrategy.force "com.squareup.okhttp3:okhttp:4.11.0"
    }
}

App模块的：
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.google.devtools.ksp' version '1.9.10-1.0.13'
}
apply plugin: 'com.didiglobal.booster'
apply plugin: 'com.alibaba.arouter'
apply plugin: 'com.google.firebase.crashlytics'

apply plugin: 'com.facebook.react'

**Comment by kuyu132** [comment]
> 用了啥别的Gradle插件？把booster放到最前面试试

我的部分配置如下，怀疑可能是ARouter造成的，但移动到arouter之前还是有问题。

项目的build.gradle:
`dependencies {
    classpath "com.android.tools.build:gradle:$agp_version"
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    classpath 'com.google.devtools.ksp:symbol-processing-api:1.9.10-1.0.13'
    classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
    classpath "com.didiglobal.booster:booster-transform-thread:$booster_version"
    // fcm
    classpath 'com.google.gms:google-services:4.4.1'
    // Add the dependency for the Crashlytics Gradle plugin
    classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
    // Add the dependency for the Performance Monitoring Gradle plugin
    classpath 'com.google.firebase:perf-plugin:1.4.2'
    classpath 'com.huawei.agconnect:agcp:1.6.0.300'
    classpath "com.github.jadepeakpoet.ARouter:arouter-register:$arouter_register_version"
    //The latest version is 0.9.1. It requires at least Gradle 5.6 and Java 8
    classpath 'com.google.protobuf:protobuf-gradle-plugin:0.9.1'
    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files

    classpath('com.facebook.react:react-native-gradle-plugin')
}

allprojects {
    configurations.configureEach {
        def versions = "1.1.0-rc01"
        resolutionStrategy.force "androidx.camera:camera-core:$versions"
        resolutionStrategy.force "androidx.camera:camera-camera2:$versions"
        resolutionStrategy.force "androidx.camera:camera-view:$versions"
        resolutionStrategy.force "androidx.camera:camera-lifecycle:$versions"

        resolutionStrategy.force "androidx.activity:activity:1.5.0"
        resolutionStrategy.force "com.facebook.react:react-android:0.72.4"
        resolutionStrategy.force "com.facebook.soloader:soloader:0.10.5"
        resolutionStrategy.force "org.bouncycastle:bcpkix-jdk15on:1.670"
        resolutionStrategy.force "org.bouncycastle:bcpkix-jdk15on:1.68"
        resolutionStrategy.force "com.squareup.okhttp3:okhttp:4.11.0"
    }
}
`

App模块的：
`plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.google.devtools.ksp' version '1.9.10-1.0.13'
}
apply plugin: 'com.didiglobal.booster'
apply plugin: 'com.alibaba.arouter'
apply plugin: 'com.google.firebase.crashlytics'

apply plugin: 'com.facebook.react'`
