### ISSUE TITLE
transformClassesWithBooster插桩任务卡死

### ISSUE THREAD

**Issue by jimmy5zhang** [didi/booster#385]
Please provide the following informations.

- System version
linux

- Java version
jdk 11

- Gradle version
7.3.3

- Android Gradle plugin version
7.2.2

- Booster version
com.didiglobal.booster:booster-gradle-plugin:4.13.0
com.didiglobal.booster:booster-transform-r-inline:4.13.0

- Stack traces
通过gradle命令后构建后，偶现出现卡死在booster插桩任务，1-2小时后，由于超时直接导致编译失败

> Task :app: transformClassesWithBoosterForSetup64Release

**Comment by neighbWang** [comment]
个人猜测，是使用Analyse之后，内存OOM导致的~ 建议在gradle.properties里面吧内存调大在尝试一下~
