### ISSUE TITLE
booster-task-compression相关问题

### ISSUE THREAD

**Issue by sihaixuan** [didi/booster#39]
1.compressProcessedRes压缩resource*.ap_ 在什么情况下起到压缩效果，我打印了resource*.ap_文件所有条目的method,都没变化，即没有起到压缩的效果，log如下：
ZipEntry name : AndroidManifest.xml ,method : 8,target ZipEntry method: 8
ZipEntry name : res/anim/abc_fade_in.xml ,method : 8,target ZipEntry method: 8
ZipEntry name : res/anim/abc_fade_out.xml ,method : 8,target ZipEntry method: 8
ZipEntry name : res/anim/abc_grow_fade_in_from_bottom.xml ,method : 8,target ZipEntry method: 8
ZipEntry name : res/drawable-v21/notification_action_background.xml ,method : 8,target ZipEntry method: 8
ZipEntry name : res/drawable/notification_bg.xml ,method : 8,target ZipEntry method: 8
ZipEntry name : res/drawable/notification_bg_low.xml ,method : 8,target ZipEntry method: 8
ZipEntry name : res/drawable-mdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png ,method : 0,target ZipEntry method: 0
ZipEntry name : res/drawable-mdpi-v4/abc_btn_check_to_on_mtrl_000.png ,method : 0,target ZipEntry method: 0
ZipEntry name : res/drawable-mdpi-v4/abc_btn_check_to_on_mtrl_015.png ,method : 0,target ZipEntry method: 0
ZipEntry name : res/drawable-mdpi-v4/abc_btn_radio_to_on_mtrl_000.png ,method : 0,target ZipEntry method: 0
...

2.RemoveRedundantFlatImages 删除多余的*.png.flat,也没效果，apk中各个限定符drawable下都有相同的图片，插件控制台log如下：
Invalid AAPT2 container file: `F:\developer_workspace\android__workspace\NewStudy\BoosterDemo\app\build\intermediates\res\merged\debug\drawable-xxxhdpi-v4_abc_ic_s
tar_half_black_16dp.png.flat`,magic = 1 / 0x1
Invalid AAPT2 container file: `F:\developer_workspace\android__workspace\NewStudy\BoosterDemo\app\build\intermediates\res\merged\debug\drawable-xxhdpi-v4_abc_text_
select_handle_left_mtrl_light.png.flat`,magic = 1 / 0x1
Invalid AAPT2 container file: `F:\developer_workspace\android__workspace\NewStudy\BoosterDemo\app\build\intermediates\res\merged\debug\drawable-hdpi-v4_abc_ic_menu
_copy_mtrl_am_alpha.png.flat`,magic = 1 / 0x1
Invalid AAPT2 container file: `F:\developer_workspace\android__workspace\NewStudy\BoosterDemo\app\build\intermediates\res\merged\debug\drawable-xxhdpi-v4_abc_text_
select_handle_middle_mtrl_dark.png.flat`,magic = 1 / 0x1
Invalid AAPT2 container file: `F:\developer_workspace\android__workspace\NewStudy\BoosterDemo\app\build\intermediates\res\merged\debug\drawable-hdpi-v4_abc_ic_menu
_cut_mtrl_alpha.png.flat`,magic = 1 / 0x1

使用BinaryParser直接解析*\intermediates\res\merged\debug\目录文件
anim_abc_fade_in.xml.flat magic = 1 , version = 223 , count = 0
anim_abc_fade_out.xml.flat magic = 1 , version = 225 , count = 0
anim_abc_grow_fade_in_from_bottom.xml.flat magic = 1 , version = 257 , count = 0
drawable-hdpi-v4_abc_ab_share_pack_mtrl_alpha.9.png.flat magic = 1 , version = 275 , count = 0
drawable-hdpi-v4_abc_btn_check_to_on_mtrl_000.png.flat magic = 1 , version = 273 , count = 0
values-af_values-af.arsc.flat magic = a01cb0a , version = 65992 , count = 13107228
values-am_values-am.arsc.flat magic = a01cb0a , version = 65992 , count = 13107228
values-ar_values-ar.arsc.flat magic = a01cb0a , version = 65992 , count = 13107228
values-b+sr+Latn_values-b+sr+Latn.arsc.flat magic = a01d70a , version = 66004 , count = 13893660

可以看出：
xml.flat magic = 1
png.flat magic = 1
arsc.flat magic = a01cb0a

跟库中flat文件的magic不符，也没起到压缩效果。

这个跟编译环境版本有关系没有？

**Comment by johnsonlee** [comment]
1. 不是所有的 zip entry 都会压缩，详见：[NO_COMPRESS](https://github.com/didi/booster/blob/master/booster-task-compression/src/main/kotlin/com/didiglobal/booster/task/compression/CompressionVariantProcessor.kt#L203)
2. `.flat` 文件没有压缩成功跟 *Android Gradle Plugin* 版本有关，3.0 - 3.1 的 AAPT2 container 跟 3.2 的 AAPT2 container 格式不兼容，试试升级到 `3.2.0`

**Comment by sihaixuan** [comment]
谢谢，您的回复，修改Android Gradle Plugin，.flat文件 magic、type都对上了，查看booster-task-compression的report.txt,压缩率最高为35.07%
35.07% intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_ 
没有出现压缩率为100%的情况，即没出现查出冗余的图片的情况。

打印file.delete操作的结果，为false. 我这边必现，文件流操作，没有关闭流？还是其他原因！

booster_version = '0.6.0'

> 1. `8` 表示 _DEFLATED_，已经压缩过就不再压缩了；另外，不是所有的 zip entry 都会压缩，详见：[NO_COMPRESS](https://github.com/didi/booster/blob/master/booster-task-compression/src/main/kotlin/com/didiglobal/booster/task/compression/CompressionVariantProcessor.kt#L203)
> 2. `.flat` 文件没有压缩成功跟 _Android Gradle Plugin_ 版本有关，3.0 - 3.1 的 AAPT2 container 跟 3.2 的 AAPT2 container 格式不兼容，试试升级到 `3.2.0`

**Comment by johnsonlee** [comment]
> 谢谢，您的回复，修改Android Gradle Plugin版本，.flat文件 magic、type都对上了，查看booster-task-compression的report.txt,压缩率最高为35.07%
> 35.07% intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_
> 没有出现压缩率为100%的情况，即没出现删除冗余的图片的情况。
> 
> 打印file.delete操作的结果，为false. 我这边必现，文件流操作，没有关闭流？还是其他原因！
> 
> booster_version = '0.6.0'
> 
> > 1. `8` 表示 _DEFLATED_，已经压缩过就不再压缩了；另外，不是所有的 zip entry 都会压缩，详见：[NO_COMPRESS](https://github.com/didi/booster/blob/master/booster-task-compression/src/main/kotlin/com/didiglobal/booster/task/compression/CompressionVariantProcessor.kt#L203)
> > 2. `.flat` 文件没有压缩成功跟 _Android Gradle Plugin_ 版本有关，3.0 - 3.1 的 AAPT2 container 跟 3.2 的 AAPT2 container 格式不兼容，试试升级到 `3.2.0`

感谢反馈，可能跟操作系统有关系，我们先验证一下，再针对此问题进行修复

**Comment by sihaixuan** [comment]
win7 ,重启电脑，打包运行，也没有出现压缩率为100%的情况

**Comment by johnsonlee** [comment]
试试最新的版本

**Comment by sihaixuan** [comment]
Booster更新至 0.15.0 ，依旧这个问题。

**Comment by johnsonlee** [comment]
是因为 Android Gradle Plugin 3.2.0 以下版本的 AAPT2 格式不兼容问题，建议升级到 3.2.0+

**Comment by johnsonlee** [comment]
@sihaixuan 试试 `v0.21.0`

**Comment by johnsonlee** [comment]
12d4c491238d692843b0ac9efd1eace7f376c92e
