### ISSUE TITLE
How use thread transform with multimode application and dynamic loading libraries

### ISSUE THREAD

**Issue by 0xera** [didi/booster#393]
I need to use thread transform in a multi-module project but I have a NoClassDefinedError at runtime. Same issue for dynamic libraries (not dynamic feature) like firebase, gms

**Comment by johnsonlee** [comment]
could you share more details?

**Comment by 0xera** [comment]
No( Because I remove this plugin. I couldn't set up it in multi nodule project, because it requires add threads instrumentation library to all modules and transformer change sources in libraries like firebase, but I can't add threads instrumentation to that libraries. At the end my app fails with RuntimeException because he can't found ShadowThread in some firebase library
