### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by tanranran** [didi/booster#4]
WARNING: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompiler(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app

**Comment by tanranran** [comment]
apply plugin: 'com.didiglobal.booster'

**Comment by johnsonlee** [comment]
Please try `ext.booster_version = 0.1.3-SNAPSHOT`, just add the following maven repo in `repositories` and rebuid:

```groovy
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
```

**Comment by johnsonlee** [comment]
[Booster v0.1.3](../releases/tag/v0.1.3) has been released
