### ISSUE TITLE
transformClassesWithBoosterForXXXDebug报错

### ISSUE THREAD

**Issue by livelitoday** [didi/booster#401]
Please provide the following informations.

- System version Win10
 
- Java version 1.8

- Gradle version 5.6.4

- Android Gradle plugin version 3.6.3

- Booster version 4.15.0

- Stack traces
Execution failed for task ':app:transformClassesWithBoosterForXXXDebug'.

kotlin.collections.CollectionsKt.maxOrNull(Ljava/lang/Iterable;)Ljava/lang/Comparable;

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by geekzxiang** [comment]
有解决么？

**Comment by zyf19930419** [comment]
has a same issure

**Comment by zyf19930419** [comment]
将Booster version 4.14.0成功了

**Comment by CodeIdeal** [comment]
@johnsonlee 

我最近用一个新项目集成booster也遇到了这个问题。

分析了下，发现应该是因为booster前段时间升级gradle之后，embeddedKotlinVersion从原来的1.3.61(gradle 6.2)升级到了1.5.31(gradle 7.4).然后在源码中大量使用了被@SinceKotlin("xxx") (其中xxx大于1.4)注释的api方法.
*gradle embeddedKotlinVersion参见: https://docs.gradle.org/current/userguide/compatibility.html#kotlin*

这样会导致仍在使用小于等于**6.7**的gradle版本(对应embeddedKotlinVersion为1.3.72)的人，在编译时使用的仍是低版本的kotlin，从而找不到在源码中使用的高版本的kotlin api.

**Comment by johnsonlee** [comment]
参考：https://johnsonlee.io/2022/12/07/do-you-really-know-kotlin-compatibility/
