### ISSUE TITLE
有个问题想咨询一下, 关于Transformer的使用

### ISSUE THREAD

**Issue by elrondliu** [didi/booster#421]
我想在transform方法中收集某些类的信息, 比如带某些注解的类
然后在postTransform(或者其它方式也可以)中将这些类信息写入到一个特定类里并打包
类似于ByteX的先扫描后transform, 这个有没有办法实现?
谢谢.

**Comment by elrondliu** [comment]
我又遇到了一个新的问题.
我想在postTransform里面生成一个新的class, 但是我拿不到transform的output路径, 这个如何解决?

**Comment by johnsonlee** [comment]
`Transformer` 里不支持拿 output，可以考虑换一种方式来实现，比如，在代码中预先创建一个空的类，然后在 transform 的时候去修改这个类
