### ISSUE TITLE
Gradle 8.0 升级报错

### ISSUE THREAD

**Issue by lyjSmile** [didi/booster#427]
Please provide the following informations.

- System version

- Java version

- Gradle version

- Android Gradle plugin version

- Booster version

- Stack traces

**Comment by lyjSmile** [comment]
* What went wrong:
A problem occurred evaluating project ':packages:snaptube'.
> Failed to apply plugin 'com.didiglobal.booster'.
   > API 'android.registerTransform' is removed.
     
     For more information, see https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-api.
     To determine what is calling android.registerTransform, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

**Comment by johnsonlee** [comment]
AGP 8.0 适配正在进行中，请参考 https://github.com/didi/booster/pull/423
