### ISSUE TITLE
线程重命名里，请问Opcodes.INVOKESPECIAL和Opcodes.NEW分开处理的原因是什么呢

### ISSUE THREAD

**Issue by maocanmao** [didi/booster#429]
Opcodes.INVOKESPECIAL 里应该已经包括了调用构造函数new thread的场景，是哪种调用方式的场景下需要单独进行Opcodes.NEW的处理呢

**Comment by johnsonlee** [comment]
两个场景：
1. 直接 `new` 一个 `Thread` 或者 `Thread` 的子类
2. 自定义 `Thread` 的构造中调用 `super(...)`
