### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by dianyuyue** [didi/booster#43]
用kotlin编写gradle插件，你们编译后的class文件去哪里找的，我发现我这边编译后的class文件里面的方法都变成空的了

**Comment by johnsonlee** [comment]
可以参考[自定义Transformer](https://github.com/didi/booster/wiki/How-to-Create-Customized-Transformer)，或者看 Booster 的源代码：[BoosterTransformInvocation.kt](https://github.com/didi/booster/blob/master/booster-gradle-plugin/src/main/kotlin/com/didiglobal/booster/gradle/BoosterTransformInvocation.kt)，如果想了解更详细的原理，可以看看 *Android Transform API*，如有疑问，请加入[Booster 社区](https://spectrum.chat/booster)讨论

**Comment by dianyuyue** [comment]
是这样的，我写完一个基于kotlin的gradle插件后，去 build/intermediates/transforms 下查看我写的插件，页面是这样的，有几个问题

1. 不知道什么会出现两个文件夹
![](https://github.com/dianyuyue/image/blob/master/TIM%E6%88%AA%E5%9B%BE20190605171336.png?raw=true)

2. 生成的class文件，方法都被清空了

![](https://github.com/dianyuyue/image/blob/master/TIM%E6%88%AA%E5%9B%BE20190605171355.png?raw=true)
![](https://github.com/dianyuyue/image/blob/master/TIM%E6%88%AA%E5%9B%BE20190605171402.png?raw=true)

虽然和这个框架没什么关联，但还是请教一下，如果booter有做这部分的处理的话，具体源码是在哪部分呢

也就是你们写完插件后，如何去插入的代码的正确性

**Comment by dianyuyue** [comment]
困惑许久，还请大佬指教

**Comment by johnsonlee** [comment]
Show me the code

**Comment by dianyuyue** [comment]
写了一个插件 booster.gradle是直接使用 booster的
 
```java
apply plugin: 'groovy'
apply plugin: 'maven'
apply from: '../gradle/booster.gradle'

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}
repositories {
    maven {
        url uri("${rootProject.projectDir}/repo")
    }
    mavenCentral()
    jcenter()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()

    implementation 'com.android.tools.build:gradle:3.4.1'
    implementation project(':base_asm')
}

group='net.sample.plugin'
version='0.0.1'

uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: uri("${rootProject.projectDir}/repo"))
        }
    }
}
```

上传到本地的maven仓库

然后就是在项目中使用这个插件

插件的功能代码是

```java
override fun visitInsn(opcode: Int) {
        if (opcode >= Opcodes.IRETURN && opcode <= Opcodes.RETURN || opcode == Opcodes.ATHROW) {
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/System", "currentTimeMillis", "()J", false)
            mv.visitVarInsn(Opcodes.LLOAD, startVarIndex)
            mv.visitInsn(Opcodes.LSUB)
            val index = newLocal(Type.LONG_TYPE)
            mv.visitVarInsn(Opcodes.LSTORE, index)
            mv.visitLdcInsn(name)
            mv.visitVarInsn(Opcodes.LLOAD, index)
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, className, "invokeMethod", "(Ljava/lang/String;J)V", false)
        }
        super.visitInsn(opcode)
    }
```

插件的功能使用上是没有问题的，这个我测试过的，主要是如果我用JAVA代码写，是可以查看到插入代码后的class文件，但是用kotlin写的话，就不太清楚去哪里找这个class文件

**Comment by johnsonlee** [comment]
最好把完整代码 push 到 GitHub 上，提供 git repo 地址

**Comment by dianyuyue** [comment]
不知道什么原因无法上传 
只能传一个压缩包了 不好意思 
地址在这 https://github.com/dianyuyue/sample

**Comment by dianyuyue** [comment]
我引用了booster测试了下，发现结果和我这边的是一样的，就是找不到被修改过的 .class文件
其实我的问题就是这一个，你们开发过程中，是如何找到编译过后的 .class文件来确认是否修改class文件成功的？

**Comment by johnsonlee** [comment]
目前 Booster 还未针对 *Android Gradle Plugin* `3.4.0` 进行适配

**Comment by dianyuyue** [comment]
貌似不是版本问题 
我是换成3.2.0进行测试的，还是找不到被修改后的 .class文件

**Comment by johnsonlee** [comment]
“找不到被修改后的 .class 文件“ 指的是以下哪种情况？
1. Transform 完成后，无法确认是否修改成功
2. 运行时加载不到被修改的 .class

**Comment by dianyuyue** [comment]
是第一种情况

**Comment by johnsonlee** [comment]
> 是第一种情况

被修改的 *JAR* 就在 *build/intermediates/transforms/booster/debug/\*.jar* 中，如果找不到，除非是 transform 过程失败导致 *JAR* 未写成功

**Comment by dianyuyue** [comment]
那么我是需要使用工具把目录下几十个的jar依次看一遍还是有其他方法呢

**Comment by johnsonlee** [comment]
如果只是想验证实验结果，用 *unzip | javap | grep* 就行

**Comment by dianyuyue** [comment]
好的 十分感谢您的解答

**Comment by dianyuyue** [comment]
你好，今天我测试了一下,发现所有的jar包都找不到修改过的，而且是自己写的代码也找不到
只能找到系统的一些class，但是代码确实是插入了，因为日志也有打印出来

**Comment by johnsonlee** [comment]
能详细描述一下你的步骤及期望的结果吗？

**Comment by dianyuyue** [comment]
我使用了jar-ui工具打开了 build/intermediates/transforms/booster/debug/*.jar 下面的所有的jar然后一一查找，没有找到对应的类，也没有找到自己编写的类，也就是自己写的代码编译过后的类不知道跑哪里去了
就是期望能够找到transform过后的 .class 文件

**Comment by johnsonlee** [comment]
试试：

```bash
find app/build/intermediates/transforms/booster/debug -name *.jar | while read jar; do
  if [ $(unzip -l $jar | grep "/ShadowToast.class" | wc -l) -gt 0 ]; then
    echo $jar
  fi
done
```

**Comment by johnsonlee** [comment]
简单一点，在 transform 的过程中，改了哪些类，属于哪个 jar，加上详细的 log 就能定位了

**Comment by dianyuyue** [comment]
请教一下，如何确定改的类是属于哪个jar包呢   build中的jar包不都是数字打头的么

**Comment by neighbWang** [comment]
使用命令行打印日志， 后面加上参数--stacktrace

**Comment by johnsonlee** [comment]
> 请教一下，如何确定改的类是属于哪个jar包呢 build中的jar包不都是数字打头的么

```kotlin
val dest = outputProvider.getContentLocation(
                        jarInput.file.absolutePath,
                        jarInput.contentTypes,
                        jarInput.scopes,
                        Format.JAR)
println("${jarInput.file} => ${dest}")
```

**Comment by dianyuyue** [comment]
好像这个也只能看到系统地class  找不到自己写的class
