### ISSUE TITLE
如何扫描dynamic-feature

### ISSUE THREAD

**Issue by zhuangdapao** [didi/booster#438]
请教大佬基于4.16.3如何扫描到dynamic-feature里的类。

demo使用https://github.com/android/codelab-android-dynamic-features/tree/master

目前在buildSrc里创建 代码如下

![image](https://github.com/didi/booster/assets/141600725/44d58454-9594-4fde-9116-544daf055ced)

打印的结果不包含feature模块里的类，看boosterTransform里需要满足 parameter.plugins.hasPlugin("com.android.dynamic-feature") 
但在app里应用插件不包含，而在dynamic模块使用booster插件则会报错
variant.getApplicationId() is not supported by dynamic-feature plugins as it cannot handle delayed setting of the application ID. Please use getApplicationIdTextResource() instead

agp版本为7.0.4
命令./gradlew clean :app:bundleRelease

**Comment by zhuangdapao** [comment]
scope指定为SCOPE_FULL_WITH_FEATURES是可以扫到该模块的类，为什么这里用parameter.plugins.hasPlugin("com.android.dynamic-feature")拦截

**Comment by zhuangdapao** [comment]
scope指定为SCOPE_FULL_WITH_FEATURES是可以扫到该模块的类。parameter.plugins.hasPlugin("com.android.dynamic-feature")但使用booster被该条件拦截

**Comment by zhuangdapao** [comment]
麻烦帮忙看看。只在base module引入 并指定包含feature的scope是可以扫描到类的，而booster这里被拦截了

**Comment by qiaoyanfei** [comment]
可以扫描到dynamic-feature了吗？
