### ISSUE TITLE
 the booster-task-analyser link is 404 - page not found when click

### ISSUE THREAD

**Issue by feng612266** [didi/booster#455]
in Performance list the booster-task-analyser link is 404 - page not found when click
![微信图片_20240401152607](https://github.com/didi/booster/assets/6754540/71f86ec2-4a7f-4576-99b4-6c7b1d8ba1d3)
![微信图片_20240401152626](https://github.com/didi/booster/assets/6754540/607039c2-0f9a-4ed5-9002-e0ed6d5c0bdb)

**Comment by johnsonlee** [comment]
No longer supported
