### ISSUE TITLE
5.0.0 这些模块弃用了吗？

### ISSUE THREAD

**Issue by mikelhm** [didi/booster#469]
<img width="739" alt="image" src="https://github.com/user-attachments/assets/9dec7d36-6900-43c5-8758-405cbcef0895">
如图 5.0.0 版本这些模块弃用了吗？ 不能再压缩Png，转换 png->webp, 删除冗余资源了??

**Comment by johnsonlee** [comment]
This is the trade-off for delivering Booster 5.0, let's find a way to get them back in the upcoming releases
