### ISSUE TITLE
不同的 com.didiglobal.booster.transform.Transformer 之间能进行排序吗？

### ISSUE THREAD

**Issue by woxin123** [didi/booster#473]
Please provide the following informations.

- System version

- Java version

- Gradle version

- Android Gradle plugin version

- Booster version

- Stack traces

**Comment by xeemoo** [comment]
Use the @Priority annotation on the Transformer to specify the priority of the Transformer.

**Comment by xeemoo** [comment]
Use the `@Priority` annotation on the Transformer to specify the priority of the Transformer (the smaller the value, the higher the priority)
