### ISSUE TITLE
请教下，支持针对单独transform配置自定义extension吗

### ISSUE THREAD

**Issue by pidanxiangjiao** [didi/booster#475]

**Comment by johnsonlee** [comment]
不支持

**Comment by yinkh** [comment]
把自己的transform写在gradle的plugin里，然后读取到extension并放到单例里存起来，在transform的时候拿出来用就行了

**Comment by pidanxiangjiao** [comment]
> 把自己的transform写在gradle的plugin里，然后读取到extension并放到单例里存起来，在transform的时候拿出来用就行了

就是需要自己写一个壳 plugin，去设置 和存储extension的属性，
然后booster的 transform 过程中 找到 自己的壳 plugin 再获取对应属性，这个链路吗

**Comment by johnsonlee** [comment]
不支持

**Comment by yinkh** [comment]
> > 把自己的transform写在gradle的plugin里，然后读取到extension并放到单例里存起来，在transform的时候拿出来用就行了
> 
> 就是需要自己写一个壳 plugin，去设置 和存储extension的属性， 然后booster的 transform 过程中 找到 自己的壳 plugin 再获取对应属性，这个链路吗

是的
