### ISSUE TITLE
加入booster后，约束布局Group 解析不了

### ISSUE THREAD

**Issue by xie123** [didi/booster#5]
![image](https://user-images.githubusercontent.com/7463283/56858427-41c17680-69ac-11e9-8108-1b479d7d7ec8.png)

之后尝试去掉 booster后，一切正常~~~

**Comment by johnsonlee** [comment]
临时解决方案：在 `buildscript` 的 `dependencies` 中把 `booster-transform-all` 替换为：

```groovy
classpath "com.didiglobal.booster:booster-transform-bugfix-toast:$booster_version"
classpath "com.didiglobal.booster:booster-transform-lint:$booster_version"
classpath "com.didiglobal.booster:booster-transform-usage:$booster_version"
```

**Comment by johnsonlee** [comment]
> ![image](https://user-images.githubusercontent.com/7463283/56858427-41c17680-69ac-11e9-8108-1b479d7d7ec8.png)
> 
> 之后尝试去掉 booster后，一切正常~~~

原因是因为 `ConstraintHelper` 用 resource name 反查 resource id，而 `R$id` 被 `booster-transform-shrink` 移除了

**Comment by johnsonlee** [comment]
Booster `v0.1.4` is available

**Comment by xie123** [comment]
![image](https://user-images.githubusercontent.com/7463283/57205794-a6578380-6ff3-11e9-99d4-85841602f069.png)

ext.booster_version = '0.2.0'
classpath 'com.android.tools.build:gradle:3.4.0'
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip

**Comment by xie123** [comment]
在我不使用Group时 ，就可以了

**Comment by johnsonlee** [comment]
麻烦粘一下 layout xml

**Comment by johnsonlee** [comment]
麻烦提供一下 `constraint-layout` 的版本

**Comment by xie123** [comment]
![image](https://user-images.githubusercontent.com/7463283/57206718-ac049780-6ffa-11e9-9285-41439d4c47db.png)

**Comment by xie123** [comment]
![image](https://user-images.githubusercontent.com/7463283/57206736-bb83e080-6ffa-11e9-9645-15aaae6cfa56.png)
布局太长了，约束布局中Group 的使用

**Comment by johnsonlee** [comment]
试试 `Booster v0.2.1-SNAPSHOT`

**Comment by xie123** [comment]
好像还是一样的

**Comment by johnsonlee** [comment]
看下 `build/reports/booster-transform-shrink/report.txt` 的第一行，像这样：

```
booster.transform.shrink.ignores=[android/support/constraint/R$id.class]
```

**Comment by xie123** [comment]
![image](https://user-images.githubusercontent.com/7463283/57214577-f8f96580-701c-11e9-921e-1d4d9dc9f779.png)
 我是zhiq直接 debug。

**Comment by johnsonlee** [comment]
貌似 Booster 的版本不对

**Comment by johnsonlee** [comment]
试试 `booster v0.2.1`
