### ISSUE TITLE
How to add Custom Extension with ASM-based Transformer

### ISSUE THREAD

**Issue by moyokoo** [didi/booster#57]

**Comment by johnsonlee** [comment]
#50

**Comment by moyokoo** [comment]
想知道如何编写自己的扩展功能  Extension 
WIKI中好像没有提供这个API

**Comment by johnsonlee** [comment]
这超出了 Booster 的范畴，参考：https://docs.gradle.org/current/userguide/custom_plugins.html

**Comment by neighbWang** [comment]
如果只是想设置自定义属性，可以使用TransformContext()方法，参照[LintTransform](https://github.com/didi/booster/blob/master/booster-transform-lint/src/main/kotlin/com/didiglobal/booster/transform/lint/LintTransformer.kt)

**Comment by moyokoo** [comment]
谢谢

**Comment by moyokoo** [comment]
你好，我看了下代码，好像和扩展功能有些出入，不太清楚要如何编写，想实现的效果如下

```java
stringPluginExt {
    enable true
    fogPackages = ['xxx.xxx.xxx']
}
```

类似这种的功能

**Comment by neighbWang** [comment]
没有支持这个功能。目前如果需要自定义一组配置，可以使用`property`属性来设置。在`ext`里面配置属性，在自定义的`transformer`里面通过`getProperty('属性名')`来拿到设置的属性。

**Comment by moyokoo** [comment]
后续考虑加入这个功能么  ext 也只能获取到字符串而已  并不能发挥Ext的全部功能
