### ISSUE TITLE
关于资源文件优化的问题

### ISSUE THREAD

**Issue by SmallStoneDD** [didi/booster#61]
接入资源优化功能
使用lottie播放assets中的图片时,图片不显示

**Comment by neighbWang** [comment]
能够提供一下assets里不显示的图片么？

**Comment by SmallStoneDD** [comment]
53.83% intermediates/merged_assets/release/out/images_loading/img_3.png                                           457        849 D:\TEST\app\build\intermediates\merged_assets\release\out\images_loading\img_3.png
49.56% intermediates/merged_assets/release/out/images_loading/img_1.png                                           448        904 D:\TEST\app\build\intermediates\merged_assets\release\out\images_loading\img_1.png
46.27% intermediates/merged_assets/release/out/images_loading/img_0.png                                           329        711 D:\TEST\app\build\intermediates\merged_assets\release\out\images_loading\img_0.png

这是report.txt其中几张图的报告
我用的gradel插件是 3.4.1 编译打包都正常

**Comment by neighbWang** [comment]
我本地没有复现该情况，能否提供一个 sample 工程的 repo 地址，便于我们分析

**Comment by neighbWang** [comment]
请使用最新的Booster版本试试，我们目前已将asset图片压缩功能关闭
