### ISSUE TITLE
transform-logcat不会打印

### ISSUE THREAD

**Issue by dany1202happy** [didi/booster#62]
version 0.13.0 booster-transform-logcat    Log.i和System.out.println的内容 都不会打印  对吗？
我测试了下，引入这个后，assemblerelease，没有Log输出，看了下，shadowlog里也没有实现

**Comment by neighbWang** [comment]
Release包下不会输出日志，Debug包下正常输出日志。

**Comment by dany1202happy** [comment]
if (context.isDebuggable || klass.name.startsWith(INSTRUMENT)) {
            return klass
        }
如果是debug包  就不会替换shadowLog吧

**Comment by neighbWang** [comment]
是的

**Comment by dany1202happy** [comment]
所以，真正的原因，应该是shadowlog里没有实现的代码  对吧？
哦，是目的就是这样，为了吧relasea包的log删掉，对吧

**Comment by dany1202happy** [comment]
我还以为是个bug
