### ISSUE TITLE
Error:Failed to resolve: com.didiglobal.booster:booster-android-instrument

### ISSUE THREAD

**Issue by dany1202happy** [didi/booster#63]
你好，请问个问题：
修改booster代码，发布到本地 version 0.13.110
uploadArchives {
        repositories.mavenDeployer {
            repository(url: 'file:./pluginlib')
        }
    }
在我自己的项目中引用：
maven {
            url uri('E:/demo/booster/booster/pluginlib')
        }
        classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version"
        classpath "com.didiglobal.booster:booster-transform-logcat:$booster_version"

会提示如下：
Error:Failed to resolve: com.didiglobal.booster:booster-android-instrument-logcat:0.13.111
<a href="openFile:F:/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

请问，如何才能通过呢？

**Comment by neighbWang** [comment]
发布版本是 `0.13.110`, 引用的版本是`0.13.111`，当然找不到啊

**Comment by dany1202happy** [comment]
描述写错了,都是110或者都是111，找不到的话，会提示这样的log.
Error:Could not find com.didiglobal.booster:booster-gradle-plugin:0.13.112.
Searched in the following locations:
    file:/C:/Program Files/Android/Android Studio1/gradle/m2repository/com/didiglobal/booster/booster-gradle-plugin/0.13.112/booster-gradle-plugin-0.13.112.pom
    file:/C:/Program Files/Android/Android Studio1/gradle/m2repository/com/didiglobal/booster/booster-gradle-plugin/0.13.112/booster-gradle-plugin-0.13.112.jar
    https://dl.google.com/dl/android/maven2/com/didiglobal/booster/booster-gradle-plugin/0.13.112/booster-gradle-plugin-0.13.112.pom
    https://dl.google.com/dl/android/maven2/com/didiglobal/booster/booster-gradle-plugin/0.13.112/booster-gradle-plugin-0.13.112.jar
    https://jcenter.bintray.com/com/didiglobal/booster/booster-gradle-plugin/0.13.112/booster-gradle-plugin-0.13.112.pom
    https://jcenter.bintray.com/com/didiglobal/booster/booster-gradle-plugin/0.13.112/booster-gradle-plugin-0.13.112.jar
    file:/E:/demo/booster/booster/pluginlib/com/didiglobal/booster/booster-gradle-plugin/0.13.112/booster-gradle-plugin-0.13.112.pom
    file:/E:/demo/booster/booster/pluginlib/com/didiglobal/booster/booster-gradle-plugin/0.13.112/booster-gradle-plugin-0.13.112.jar
Required by:
    project :

**Comment by dany1202happy** [comment]
发布的时候，我把 signing相关的都注释掉了，这个没关系吧？所有的instrument都找不到，如果导入transfor-all的话，log如下
//    apply plugin: 'signing'

Error:Failed to resolve: com.didiglobal.booster:booster-android-instrument-toast:0.13.111
<a href="openFile:F:/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:Failed to resolve: com.didiglobal.booster:booster-android-instrument-logcat:0.13.111
<a href="openFile:F:/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:Failed to resolve: com.didiglobal.booster:booster-android-instrument-activity-thread:0.13.111
<a href="openFile:F:/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:Failed to resolve: com.didiglobal.booster:booster-android-instrument-finalizer-watchdog-daemon:0.13.111
<a href="openFile:F:/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:Failed to resolve: com.didiglobal.booster:booster-android-instrument-media-player:0.13.111
<a href="openFile:F:/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:Failed to resolve: com.didiglobal.booster:booster-android-instrument-res-check:0.13.111
<a href="openFile:F:/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:Failed to resolve: com.didiglobal.booster:booster-android-instrument-shared-preferences:0.13.111
<a href="openFile:F:/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:Failed to resolve: com.didiglobal.booster:booster-android-instrument-thread:0.13.111
<a href="openFile:F:/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:Failed to resolve: com.didiglobal.booster:booster-android-instrument-webview:0.13.111
<a href="openFile:F:/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by neighbWang** [comment]
1. signing的删掉没关系. 把项目引用的url换成你upload url一样，试试。不要用uri的方式来写。
2. 如果只是上传本地测试的话，可以使用`./gradlew clean install`命令上传本地仓库中，在测试工程里面添加` mavenLocal()`地址
