### ISSUE TITLE
gradlew showArtifacts --stacktrace

### ISSUE THREAD

**Issue by dany1202happy** [didi/booster#64]
Caused by: java.lang.BootstrapMethodError: call site initialization exception
        at com.didiglobal.booster.gradle.VariantScopeV30.getAllArtifacts(VariantScopeV30.java:81)
        at com.didiglobal.booster.gradle.VariantScopeKt$ALL_ARTIFACTS_GETTER$3.invoke(VariantScope.kt:10)
        at com.didiglobal.booster.gradle.VariantScopeKt$ALL_ARTIFACTS_GETTER$3.invoke(VariantScope.kt)
        at com.didiglobal.booster.gradle.VariantScopeKt.getAllArtifacts(VariantScope.kt:119)
        at com.didiglobal.booster.task.artifact.ArtifactsResolver.run(ArtifactsResolver.kt:15)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

**Comment by johnsonlee** [comment]
请提供以下信息：
- Gradle 版本
- Android Gradle Plugin 版本
-  Booster 版本

**Comment by dany1202happy** [comment]
i test with gradle-4.1/4.2/4.4   plugin 3.3.0/3.0.0 booster 0.13.0/0.10.0/0.6.0 all failed with the same log

**Comment by neighbWang** [comment]
Please upgrade your Gradle version to 4.6,  Android Gradle Plugin version to 3.2.1,  and retry.

**Comment by dany1202happy** [comment]
distributionUrl=file:/d:/tools/gradle-4.6-all.zip
ext.booster_version = '0.13.0'
classpath 'com.android.tools.build:gradle:3.2.1'
still failed with the same log
so, i just want to know,what is this task's result,what will print,please?

**Comment by neighbWang** [comment]
the task will execute and  print like this ：
```
...................................ANNOTATIONS_ZIP : []
...............DATA_BINDING_LAYOUT_INFO_TYPE_MERGE : []
.................FEATURE_DATA_BINDING_FEATURE_INFO : []
................................ABI_PACKAGED_SPLIT : []
.....................................GENERATED_SRC : []
..................................MERGED_MANIFESTS : [/Users/neighbWang/Documents/android/demo/app/build/intermediates/merged_manifests/release/processReleaseManifest/merged]
.
.
.
.
...........................RUNTIME_R_CLASS_CLASSES : []
.........................ANNOTATION_PROCESSOR_LIST : [/Users/neighbWang/Documents/android/demo/app/build/intermediates/annotation_processor_list/release/javaPreCompileRelease/annotationProcessors.json]
.......................................ALL_CLASSES : [/Users/neighbWang/Documents/android/demo/app/build/intermediates/javac/release/compileReleaseJavaWithJavac/classes]
........................COMPATIBLE_SCREEN_MANIFEST : [/Users/neighbWang/Documents/android/demo/app/build/intermediates/compatible_screen_manifest/release/createReleaseCompatibleScreenManifests/out]
................................AAR_LIBS_DIRECTORY : []
...............................................APK : [/Users/neighbWang/Documents/android/demo/app/build/outputs/apk/release]
..........................DEFINED_ONLY_SYMBOL_LIST : []

```

**Comment by dany1202happy** [comment]
thank u

**Comment by dany1202happy** [comment]
3.2.1 works well ,thanks
