### ISSUE TITLE
Process 'command 'cacls'' finished with non-zero exit value 87

### ISSUE THREAD

**Issue by xinnian25** [didi/booster#70]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installCwebp.exe'.
> Process 'command 'cacls'' finished with non-zero exit value 87

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

这个如何解决啊？

**Comment by johnsonlee** [comment]
请提供以下信息：

- OS Version
- Android Gradle Plugin Version
- Booster Version

**Comment by johnsonlee** [comment]
Duplicate of #29
