### ISSUE TITLE
快速上手文档上版本0.16.0，然而这个版本还没发布？

### ISSUE THREAD

**Issue by clzd0792** [didi/booster#71]

**Comment by neighbWang** [comment]
请暂时使用 0.15.0版本。

**Comment by johnsonlee** [comment]
OSS 同步到 maven central 需要一段时间，预计今晚会同步完成

**Comment by johnsonlee** [comment]
或者可以在 `repositories` 里加上 OSS 的 maven 地址来使用 `0.16.0`：

```groovy
maven { url 'https://oss.sonatype.org/content/repositories/public' }
```

**Comment by johnsonlee** [comment]
参考：#1

**Comment by johnsonlee** [comment]
`0.16.0` is now available in [Maven Central](https://search.maven.org/search?q=com.didiglobal.booster)
