### ISSUE TITLE
想要定制化Transformer，具体怎么做

### ISSUE THREAD

**Issue by scuzoutao** [didi/booster#72]
wiki上说可以将类文件放在${rootProject}/buildSrc/src 这个目录下

**Comment by neighbWang** [comment]
详见[How-to-Create-Customized-Transformer](https://github.com/didi/booster/wiki/How-to-Create-Customized-Transformer)

**Comment by scuzoutao** [comment]
比如说我自己写了一个MyTransformer.kt 这个kt文件，然后在项目的根目录下面创建 buildSrc/src，把这个塞进去就可以了吗，然后在 project  build.gradle里面去加一下 classpath "com.didiglobal.booster:booster-gradle-plugin:$booster_version" ，差不多是这样吗？

**Comment by neighbWang** [comment]
不是的。BuildSrc的用法参照Gradle文档[Use buildSrc to abstract imperative logic](https://docs.gradle.org/current/userguide/plugins.html)，或者参照Booster在BuildSrc目录下的写法[Booster/BuildSrc](https://github.com/didi/booster/tree/master/buildSrc).

**Comment by neighbWang** [comment]
#74

**Comment by johnsonlee** [comment]
参考：https://github.com/booster-sample/
