### ISSUE TITLE
.dot转换成png

### ISSUE THREAD

**Issue by wobuaihuangjun** [didi/booster#75]
请教下怎么将.dot转换成png，尝试了很多次都不行。
如图：
![image](https://user-images.githubusercontent.com/10093673/60225694-65287500-98ba-11e9-9156-2b359e239c1e.png)

**Comment by neighbWang** [comment]
需要使用转换工具，例如 `Graphviz`

**Comment by johnsonlee** [comment]
https://graphviz.gitlab.io/download/

**Comment by wobuaihuangjun** [comment]
成功了，thanks

**Comment by ouyangpeng** [comment]
总结一下： https://ouyangpeng.blog.csdn.net/article/details/100925405
