### ISSUE TITLE
Exception when running with Gradle

### ISSUE THREAD

**Issue by lucas34** [didi/booster#77]
Hi, I got this exception after adding booster

```
NoSuchElementException: Collection contains no element matching the predicate.
	at com.didiglobal.booster.gradle.TransformInvocationKt.getVariant(TransformInvocation.kt:79)
	at com.didiglobal.booster.gradle.TransformInvocationKt.getApplicationId(TransformInvocation.kt:61)
	at com.didiglobal.booster.gradle.BoosterTransformInvocation.<init>(BoosterTransformInvocation.kt:66)
```

**Comment by johnsonlee** [comment]
Could you please provide the following information?

- Android gradle plugin version
- The `build.gradle` of the app project (Optional)

**Comment by lucas34** [comment]
I'm using Gradle plugin 3.4.1 and gradle 5.4.1

**Comment by johnsonlee** [comment]
It might be caused by the order of plugins, try to use the following order:

```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.didiglobal.booster'
}
```

**Comment by lucas34** [comment]
Same issue. Order does't change. Event if I only use 

```
apply plugin: 'com.didiglobal.booster'
```

**Comment by johnsonlee** [comment]
I can not reproduce your issue, so I pushed a sample project at [app-kotlin-dsl](https://github.com/boostersamples/app-kotlin-dsl), please check it.

**Comment by lucas34** [comment]
I'm able to narrow down the issue. When running in local everything works fine but was failing on the CI. Turns out it's using a custom Jacoco job and rely on `testDebug`.

I'll work around the issue by disabling the plugin for tasks made to run tests and enabling for other CI task. So far no issue.

**Comment by johnsonlee** [comment]
Please try the latest snapshot version `0.25.0-SNAPSHOT`
