### ISSUE TITLE
mac电脑编译程序打包安装之后，找不到xml对应的id，程序崩溃

### ISSUE THREAD

**Issue by juejishala** [didi/booster#86]
Please provide the following informations.

- System version

- Java version

- Gradle version

- Android Gradle plugin version

- Booster version

- Stack traces

**Comment by neighbWang** [comment]
1. 能否可以按照模板提供一下系统相关详细信息？
2. 辛苦检查一下/build/intermediates/symbols/debug（release）目录下的R.txt文件中是否存在对应的资源Id

**Comment by juejishala** [comment]
macos: 10.14.5 (18F203)
javac: 1.8.0_192
gradle: 5.1.1
gradle-plugin: 3.4.2
资源文件的id在R文件和移除的里面都能找到也是同一个值，statcktrace文件暂时没有

**Comment by neighbWang** [comment]
Booster是从R文件里面读取资源Id, 并在代码里面把对应代码替换掉。单从您的描述定位不到原因，能否提供一个Sample Repo来定位一下问题？
