### ISSUE TITLE
windows电脑下如何配置pngquant？

### ISSUE THREAD

**Issue by juejishala** [didi/booster#87]
Please provide the following informations.

- System version

- Java version

- Gradle version

- Android Gradle plugin version

- Booster version

- Stack traces

**Comment by neighbWang** [comment]
需要本地安装 pngquant，然后参照[booster-task-compression.README](https://github.com/didi/booster/tree/master/booster-task-compression) 进行配置.

**Comment by juejishala** [comment]
assert文件夹中的如何添加到压缩忽略文件呢？

**Comment by neighbWang** [comment]
Booster没有设置忽略图片文件的功能

**Comment by neighbWang** [comment]
请使用最新版本的booster代码，新版本booster已经关闭asset目录下的图片压缩功能
