### ISSUE TITLE
NoSuchFieldError: No static field TAG of type Ljava/lang/String;

### ISSUE THREAD

**Issue by JianGsHanz** [didi/booster#88]
- Booster version 0.22.0

- Stack traces
NoSuchFieldError: No static field TAG of type Ljava/lang/String;
错误指向下面这个类Rom

report.txt ->

Remove `com//utils/Rom.ROM_EMUI : Ljava/lang/String;` = "EMUI"
Remove `com/utils/Rom.ROM_FLYME : Ljava/lang/String;` = "FLYME"
Remove `com/utils/Rom.ROM_OPPO : Ljava/lang/String;` = "OPPO"
Remove `com/utils/Rom.ROM_SMARTISAN : Ljava/lang/String;` = "SMARTISAN"
Remove `com/utils/Rom.ROM_VIVO : Ljava/lang/String;` = "VIVO"
Remove `com/utils/Rom.ROM_QIKU : Ljava/lang/String;` = "QIKU"
Remove `com/utils/Rom.KEY_VERSION_MIUI : Ljava/lang/String;` = "ro.miui.ui.version.name"
Remove `com/utils/Rom.KEY_VERSION_EMUI : Ljava/lang/String;` = "ro.build.version.emui"
Remove `com/utils/Rom.KEY_VERSION_OPPO : Ljava/lang/String;` = "ro.build.version.opporom"
Remove `com/utils/Rom.KEY_VERSION_SMARTISAN : Ljava/lang/String;` = "ro.smartisan.version"
Remove `com/utils/Rom.KEY_VERSION_VIVO : Ljava/lang/String;` = "ro.vivo.os.version"

**Comment by johnsonlee** [comment]
可以配置 ignores 规则忽略 `com.utils.Rom` 这个类，参考：https://github.com/didi/booster/blob/master/booster-transform-shrink/README.md

**Comment by JianGsHanz** [comment]
> 可以配置 ignores 规则忽略 `com.utils.Rom` 这个类，参考：https://github.com/didi/booster/blob/master/booster-transform-shrink/README.md

嗯，是知道这个类，但是不知道什么格式。刚刚搞好，是这种格式 booster.transform.shrink.ignores =  com/utils/* 
多谢

**Comment by neighbWang** [comment]
请问，您的工程代码是用kotlin写的么？

**Comment by JianGsHanz** [comment]
> 请问，您的工程代码是用kotlin写的么？

是的，这个Rom类是用kotlin写的

**Comment by SusionSuc** [comment]
> 请问，您的工程代码是用kotlin写的么？

好像是对Kotlin的兼容有问题，我引入后，Kotlin的Object类中的 String常量也被删除了

**Comment by johnsonlee** [comment]
please try the latest version `0.23.0-SNAPSHOT` or `0.23.0`
