### ISSUE TITLE
1、不支持Instant Run，希望可以提供开关，在debug模式下禁用booster；2、webp图片格式会增加内存占用，不适合所有场景，希望可以提供开关，不进行图片压缩

### ISSUE THREAD

**Issue by lcodecorex** [didi/booster#92]
如题

**Comment by johnsonlee** [comment]
1. debug 模式下禁用 booster 可以考虑在下个版本中增加
2. webp 是官网推荐的优化方案之一，是否启用 webp 跟 target SDK version 有关，不是所有版本有启有

**Comment by johnsonlee** [comment]
参考解决方案：https://booster.johnsonlee.io/getting-started.html (仅在 Release 构建中使用 Booster 模块)

**Comment by johnsonlee** [comment]
另外，可以通过 `booster.task.compression.cwebp.option.quality` 指定压缩质量，请参考：[自定义压缩质量](https://booster.johnsonlee.io/feature/shrink/webp-compression.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8E%8B%E7%BC%A9%E8%B4%A8%E9%87%8F)
