### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by forJrking** [didi/booster#93]
Please provide the following informations.

- System version  5.1,6.0,6.0.1

- Java version  1.8

- Gradle version   5.1.1

- Android Gradle plugin version  3.4.0

- Booster version 0.22.0

java.lang.ClassCastException:java.lang.Class cannot be cast to java.util.concurrent.ThreadPoolExecutor$Worker
--
 java.util.concurrent.ThreadPoolExecutor.interruptIdleWorkers(ThreadPoolExecutor.java:756)
java.util.concurrent.ThreadPoolExecutor.interruptIdleWorkers(ThreadPoolExecutor.java:779)
java.util.concurrent.ThreadPoolExecutor.allowCoreThreadTimeOut(ThreadPoolExecutor.java:1615)
com.didiglobal.booster.instrument.ShadowExecutors.java.util.concurrent.ExecutorService newOptimizedCachedThreadPool(java.lang.String)(SourceFile:7)
org.greenrobot.eventbus.EventBusBuilder.void <clinit>()(SourceFile:1)
org.greenrobot.eventbus.EventBus.void <clinit>()(SourceFile:1)

**Comment by johnsonlee** [comment]
麻烦提供一下报异常的 class 文件

**Comment by neighbWang** [comment]
请试一下最新的Booster版本
