### ISSUE TITLE
booster-transform-activity-thread - 处理系统 Crash

### ISSUE THREAD

**Issue by ouyangpeng** [didi/booster#95]
想问问 这个是不是修复的到底是android.app.ActivityThread的什么问题？

可能我没有遇到过此问题

**Comment by johnsonlee** [comment]
看 catch 的异常类型就知道了，但是引发同一个异常类型的原因是多个，这个得结合 APM 工具来看

**Comment by yzhiw** [comment]
@johnsonlee catch了异常以后不会造成app黑屏或者显示不正常吗？ 比如Activity onCreate出了异常，虽然catch了，但是后续启动流程不会有问题吗？

**Comment by johnsonlee** [comment]
> @johnsonlee catch了异常以后不会造成app黑屏或者显示不正常吗？ 比如Activity onCreate出了异常，虽然catch了，但是后续启动流程不会有问题吗？

只会 catch 由系统引发的异常，如果是 Activity onCreate 出了异常，是不会 catch 的

**Comment by Terrorist-1** [comment]
我想hook 所有的闪退、可以做到吗？

**Comment by Terrorist-1** [comment]
@johnsonlee

**Comment by johnsonlee** [comment]
拦截主线程 looper
