### ISSUE TITLE
booster-transform-res-check - 检查覆盖安装导致的 Resources 和 Assets 未加载的 Bug

### ISSUE THREAD

**Issue by ouyangpeng** [didi/booster#96]
覆盖安装导致的 Resources 和 Assets 未加载的 Bug

这个bug出现的场景能否描述下？   似乎没遇到过

**Comment by johnsonlee** [comment]
这种 case 量很少，一般出现在 Android 7.0+ 应用升级后首次重启

**Comment by snpmyn** [comment]
覆盖安装时，控件报空指针导致闪退。必须clean -> rebuild 才可以。请关注一下

**Comment by snpmyn** [comment]
> 这种 case 量很少，一般出现在 Android 7.0+ 应用升级后首次重启

覆盖安装时，页面控件报空指针导致闪退。必须clean -> rebuild 才可以。请关注一下

**Comment by johnsonlee** [comment]
> > 这种 case 量很少，一般出现在 Android 7.0+ 应用升级后首次重启
> 
> 覆盖安装时，页面控件报空指针导致闪退。必须clean -> rebuild 才可以。请关注一下

不是一回事儿，是系统的 bug

**Comment by snpmyn** [comment]
> > > 这种 case 量很少，一般出现在 Android 7.0+ 应用升级后首次重启
> > 
> > 
> > 覆盖安装时，页面控件报空指针导致闪退。必须clean -> rebuild 才可以。请关注一下
> 
> 不是一回事儿，是系统的 bug

那如何才能避免？

**Comment by johnsonlee** [comment]
> > > > 这种 case 量很少，一般出现在 Android 7.0+ 应用升级后首次重启
> > > 
> > > 
> > > 覆盖安装时，页面控件报空指针导致闪退。必须clean -> rebuild 才可以。请关注一下
> > 
> > 
> > 不是一回事儿，是系统的 bug
> 
> 那如何才能避免？

重启APP，所以我们的方案是直接 kill 进程

**Comment by snpmyn** [comment]
> > > > > 这种 case 量很少，一般出现在 Android 7.0+ 应用升级后首次重启
> > > > 
> > > > 
> > > > 覆盖安装时，页面控件报空指针导致闪退。必须clean -> rebuild 才可以。请关注一下
> > > 
> > > 
> > > 不是一回事儿，是系统的 bug
> > 
> > 
> > 那如何才能避免？
> 
> 重启APP，所以我们的方案是直接 kill 进程

但是如果不使用 booster 的话，是没有这个问题的。不知道什么原因

**Comment by johnsonlee** [comment]
麻烦提供一下堆栈信息

**Comment by neighbWang** [comment]
需要检查下cache的构建信息。
