### ISSUE TITLE
booster-transform-finalizer-watchdog-daemon - 修复 finalizer 导致的 TimeoutException

### ISSUE THREAD

**Issue by ouyangpeng** [didi/booster#97]
这个主要是采取下面的方案一来做的吧

![image](https://user-images.githubusercontent.com/5885735/65137153-6988a800-da3b-11e9-895c-07619b178c41.png)

方案一
![image](https://user-images.githubusercontent.com/5885735/65137179-73121000-da3b-11e9-8285-7d9d382a100d.png)

方案二
```java
try {
    Class<?> c = Class.forName("java.lang.Daemons");
    Field maxField = c.getDeclaredField("MAX_FINALIZE_NANOS");
    maxField.setAccessible(true);
    maxField.set(null, Long.MAX_VALUE);
} catch (ClassNotFoundException e) {
    e.printStackTrace();
} catch (NoSuchFieldException e) {
    e.printStackTrace();
} catch (IllegalAccessException e) {
    e.printStackTrace();
}
```

https://blog.csdn.net/sinat_28496853/article/details/79115941

**Comment by neighbWang** [comment]
采用方案一。详见[FinalizerWatchdogDaemonKiller](https://github.com/didi/booster/blob/master/booster-android-instrument-finalizer-watchdog-daemon/src/main/java/com/didiglobal/booster/instrument/FinalizerWatchdogDaemonKiller.java)

**Comment by ouyangpeng** [comment]
@neighbWang 代码之前看完了，只是证实一下
